package gregicadditions.recipes.chain;

import gregtech.api.recipes.ingredients.IntCircuitIngredient;
import gregtech.api.unification.OreDictUnifier;
import gregtech.api.unification.material.MarkerMaterials;

import static gregicadditions.GAMaterials.*;
import static gregicadditions.recipes.GARecipeMaps.*;
import static gregtech.api.recipes.RecipeMaps.*;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.ore.OrePrefix.craftingLens;
import static gregtech.api.unification.ore.OrePrefix.dust;

public class FullereneChain {
    public static void init() {
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Bromine.getFluid(1000))
                .fluidInputs(Naphtalene.getFluid(1000))
                .fluidInputs(SodiumCyanide.getFluid(1000))
                .outputs(OreDictUnifier.get(dust, Sodium))
                .outputs(Cyanonaphtalene.getItemStack(2))
                .EUt(8000000)
                .duration(10)
                .buildAndRegister();
        MIXER_RECIPES.recipeBuilder()
                .input(dust, Tin)
                .fluidInputs(Chlorine.getFluid(1000))
                .outputs(TinChloride.getItemStack(2))
                .EUt(50000)
                .duration(10)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(Cyanonaphtalene.getItemStack())
                .fluidInputs(Water.getFluid(1000))
                .fluidInputs(HydrochloricAcid.getFluid(1000))
                .notConsumable(TinChloride.getItemStack())
                .fluidOutputs(Naphthaldehyde.getFluid(3000))
                .EUt(8000000)
                .duration(10)
                .buildAndRegister();
        CHEMICAL_PLANT_RECIPES.recipeBuilder()
                .fluidInputs(Naphthaldehyde.getFluid(1000))
                .input(dust, SodiumHydroxide)
                .fluidInputs(EthylBenzene.getFluid(1000))
                .fluidInputs(EthyleneOxide.getFluid(1000))
                .fluidInputs(HydrobromicAcid.getFluid(1000))
                .notConsumable(dust, Iodine)
                .notConsumable(Triphenylphosphine.getItemStack())
                .outputs(Methylbenzophenanthrene.getItemStack(5))
                .EUt(8000000)
                .duration(50)
                .buildAndRegister();
        CHEMICAL_PLANT_RECIPES.recipeBuilder()
                .inputs(PotassiumCyanide.getItemStack())
                .inputs(Methylbenzophenanthrene.getItemStack())
                .inputs(Bromosuccinimide.getItemStack())
                .outputs(Benzophenanthrenylacetonitrile.getItemStack(3))
                .EUt(8000000)
                .duration(100)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .inputs(Benzophenanthrenylacetonitrile.getItemStack())
                .fluidInputs(PotassiumHydroxide.getFluid(1000))
                .notConsumable(TiAlChloride.getItemStack())
                .fluidInputs(ThionylChloride.getFluid(1000))
                .fluidInputs(Water.getFluid(1000))
                .outputs(UnfoldedFullerene.getItemStack(5))
                .EUt(8000000)
                .duration(150)
                .buildAndRegister();
        LARGE_ENGRAVER_RECIPES.recipeBuilder()
                .notConsumable(craftingLens, MarkerMaterials.Color.Magenta)
                .inputs(UnfoldedFullerene.getItemStack())
                .outputs(Fullerene.getItemStack())
                .EUt(8000000)
                .duration(100)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Chlorine.getFluid(1000))
                .input(dust, Phosphorus)
                .fluidOutputs(PhosphorusChloride.getFluid(2000))
                .EUt(480)
                .duration(300)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Sodium)
                .fluidInputs(PhosphorusChloride.getFluid(1000))
                .fluidInputs(Chlorobenzene.getFluid(1000))
                .outputs(OreDictUnifier.get(dust, Salt))
                .outputs(Triphenylphosphine.getItemStack(2))
                .EUt(8000000)
                .duration(150)
                .buildAndRegister();
        BIO_REACTOR_RECIPES.recipeBuilder()
                .inputs(EschericiaColi.getItemStack())
                .input(dust, Sugar)
                .EUt(125000)
                .outputs(SuccinicAcid.getItemStack())
                .duration(500)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .inputs(SuccinicAcid.getItemStack())
                .fluidInputs(Ammonia.getFluid(1000))
                .fluidOutputs(Water.getFluid(1000))
                .outputs(Succinimide.getItemStack())
                .EUt(8000000)
                .duration(50)
                .blastFurnaceTemp(10000)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(Succinimide.getItemStack())
                .input(dust, SodiumHydroxide)
                .fluidInputs(Bromine.getFluid(1000))
                .outputs(Bromosuccinimide.getItemStack(3))
                .EUt(8000000)
                .duration(100)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(SulfurTrioxide.getFluid(1000))
                .input(dust, Sulfur)
                .fluidInputs(Chlorine.getFluid(1000))
                .fluidOutputs(SulfurDioxide.getFluid(1000))
                .fluidOutputs(ThionylChloride.getFluid(2000))
                .EUt(8000000)
                .duration(200)
                .buildAndRegister();
        MIXER_RECIPES.recipeBuilder()
                .input(dust, Titanium)
                .input(dust, Aluminium)
                .fluidInputs(Chlorine.getFluid(1000))
                .EUt(2000000)
                .duration(50)
                .outputs(TiAlChloride.getItemStack(3))
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(HydrogenCyanide.getFluid(1000))
                .fluidInputs(PotassiumHydroxide.getFluid(1000))
                .outputs(PotassiumCyanide.getItemStack())
                .fluidOutputs(Water.getFluid(1000))
                .EUt(122880)
                .duration(250)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, RockSalt, 2)
                .fluidInputs(Water.getFluid(2000))
                .fluidOutputs(PotassiumHydroxide.getFluid(2000))
                .fluidOutputs(Chlorine.getFluid(1000))
                .fluidOutputs(Hydrogen.getFluid(1000))
                .EUt(122880)
                .duration(150)
                .buildAndRegister();
        CHEMICAL_PLANT_RECIPES.recipeBuilder()
                .fluidInputs(IronChloride.getFluid(1000))
                .input(dust, SodiumHydroxide)
                .input(dust, Sugar)//Fructose?
                .fluidInputs(Magnesium.getFluid(144))
                .fluidInputs(Bromine.getFluid(1000))
                .notConsumable(PdIrReOCeOS.getItemStack())
                .inputs(ZeoliteSievingPellets.getItemStack())
                .fluidOutputs(Ferrocene.getFluid(3000))
                .fluidOutputs(Water.getFluid(1000))
                .outputs(MgClBrominide.getItemStack())
                .outputs(WetZeoliteSievingPellets.getItemStack())
                .EUt(8000000)
                .duration(200)
                .buildAndRegister();
        LARGE_MIXER_RECIPES.recipeBuilder()
                .input(dust, Palladium)
                .input(dust, Iridium)
                .input(dust, Rhenium)
                .input(dust, Cerium)
                .input(dust, Osmium)
                .input(dust, Silicon)
                .fluidInputs(Oxygen.getFluid(4000))
                .outputs(PdIrReOCeOS.getItemStack(5))
                .EUt(2000000)
                .duration(5)
                .buildAndRegister();
        CHEMICAL_PLANT_RECIPES.recipeBuilder()
                .fluidInputs(Ferrocene.getFluid(1000))
                .fluidInputs(Chloroform.getFluid(1000))
                .inputs(Fullerene.getItemStack())
                .inputs(SodiumEthoxide.getItemStack())
                .fluidInputs(Toluene.getFluid(1000))
                .notConsumable(AluminiumChloride.getItemStack())
                .inputs(NMethylglicine.getItemStack())
                .outputs(OreDictUnifier.get(dust, Salt))
                .fluidOutputs(Ferrocenylfulleropyrrolidine.getFluid(5000))
                .EUt(8000000)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, SodiumHydroxide)
                .fluidInputs(Ethanol.getFluid(1000))
                .fluidOutputs(Water.getFluid(1000))
                .outputs(SodiumEthoxide.getItemStack())
                .EUt(500000)
                .duration(10)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Methylamine.getFluid(1000))
                .fluidInputs(Chlorine.getFluid(1000))
                .fluidInputs(AceticAcid.getFluid(1000))
                .fluidInputs(AceticAnhydride.getFluid(10))
                .outputs(NMethylglicine.getItemStack(3))
                .EUt(8000000)
                .duration(100)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Ammonia.getFluid(1000))
                .fluidInputs(Methanol.getFluid(1000))
                .notConsumable(dust, AluminoSilicateWool)
                .notConsumable(new IntCircuitIngredient(3))
                .fluidOutputs(Methylamine.getFluid(2000))
                .EUt(122880)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Ferrocenylfulleropyrrolidine.getFluid(1000))
                .input(dust, Palladium)
                .fluidInputs(AceticAcid.getFluid(1000))
                .fluidInputs(NitricAcid.getFluid(1000))
                .outputs(PdFullereneMatrix.getItemStack())
                .EUt(8000000)
                .duration(100)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(HydrogenSulfide.getFluid(1000))
                .fluidInputs(Methanol.getFluid(1000))
                .fluidOutputs(Dimethylsulfide.getFluid(2000))
                .EUt(8000000)
                .duration(50)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Chlorine.getFluid(1000))
                .fluidInputs(Toluene.getFluid(1000))
                .fluidInputs(Water.getFluid(1000))
                .fluidOutputs(BenzoylChloride.getFluid(3000))
                .EUt(8000000)
                .duration(100)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Hydrogen.getFluid(1000))
                .fluidInputs(Bromine.getFluid(1000))
                .fluidInputs(CarbonMonoxde.getFluid(1000))
                .fluidInputs(Butene.getFluid(1000))
                .fluidInputs(Benzene.getFluid(1000))
                .fluidOutputs(HydrobromicAcid.getFluid(1000))
                .fluidOutputs(Phenylpentanoicacid.getFluid(4000))
                .EUt(8000000)
                .duration(300)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .inputs(Fullerene.getItemStack())
                .fluidInputs(Phenylpentanoicacid.getFluid(1000))
                .inputs(Bromosuccinimide.getItemStack(1))
                .fluidInputs(Dimethylsulfide.getFluid(1000))
                .fluidInputs(BenzoylChloride.getFluid(1000))
                .fluidInputs(Silvertetrafluoroborate.getFluid(10))
                .fluidOutputs(PCBA.getFluid(4000))
                .EUt(8000000)
                .duration(250)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(BoronFluoride.getFluid(1000))
                .input(dust, SilverOxide)
                .fluidInputs(Benzene.getFluid(10))
                .fluidOutputs(Silvertetrafluoroborate.getFluid(2000))
                .EUt(122880)
                .duration(50)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Ammonia.getFluid(1000))
                .fluidInputs(Phosgene.getFluid(1000))
                .fluidInputs(IsopropylAlcohol.getFluid(1000))
                .notConsumable(Triphenylphosphine.getItemStack())
                .fluidOutputs(Diisopropylcarbodiimide.getFluid(3000))
                .EUt(8000000)
                .duration(150)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(CarbonMonoxde.getFluid(1000))
                .fluidInputs(Chlorine.getFluid(1000))
                .notConsumable(dust, Carbon)
                .fluidOutputs(Phosgene.getFluid(2000))
                .EUt(8000000)
                .duration(50)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Dimethylamine.getFluid(1000))
                .fluidInputs(Pyridine.getFluid(1000))
                .fluidInputs(Chlorine.getFluid(1000))
                .input(dust, SodiumHydroxide)
                .outputs(OreDictUnifier.get(dust, Salt))
                .outputs(Dimethylaminopyridine.getItemStack(3))
                .EUt(8000000)
                .duration(200)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(PCBA.getFluid(1000))
                .fluidInputs(SulfuricAcid.getFluid(1000))
                .fluidInputs(Diisopropylcarbodiimide.getFluid(1000))
                .input(dust, SodiumHydroxide)
                .fluidInputs(Toluene.getFluid(1000))
                .fluidInputs(Styrene.getFluid(1000))
                .inputs(Dimethylaminopyridine.getItemStack())
                .fluidOutputs(PCBS.getFluid(7000))
                .EUt(8000000)
                .duration(400)
                .buildAndRegister();
        CHEMICAL_BATH_RECIPES.recipeBuilder()
                .fluidInputs(PCBS.getFluid(1000))
                .inputs(PdFullereneMatrix.getItemStack())
                .outputs(OreDictUnifier.get(dust, FullerenePolymerMatrix, 2))
                .EUt(8000000)
                .duration(100)
                .buildAndRegister();

    }
}
