package gregicadditions.recipes.chain;

import gregtech.api.unification.OreDictUnifier;

import static gregicadditions.GAMaterials.*;
import static gregicadditions.recipes.GARecipeMaps.*;
import static gregicadditions.recipes.GARecipeMaps.LARGE_MIXER_RECIPES;
import static gregtech.api.recipes.RecipeMaps.*;
import static gregtech.api.recipes.RecipeMaps.DISTILLATION_RECIPES;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.ore.OrePrefix.dust;
import static gregtech.api.unification.ore.OrePrefix.dustTiny;

public class NaquadahChain {

    public static void init() {
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, NaquadricCompound)
                .fluidInputs(AquaRegia.getFluid(1000))
                .fluidOutputs(NaquadricSolution.getFluid(1000))
                .EUt(7680)
                .duration(100)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, EnrichedNaquadricCompound)
                .fluidInputs(AquaRegia.getFluid(1000))
                .fluidOutputs(EnrichedNaquadricSolution.getFluid(1000))
                .EUt(7680)
                .duration(100)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, NaquadriaticCompound)
                .fluidInputs(AquaRegia.getFluid(1000))
                .fluidOutputs(NaquadriaticSolution.getFluid(1000))
                .EUt(7680)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .fluidInputs(Oxygen.getFluid(3000))
                .input(dust, Antimony, 2)
                .outputs(OreDictUnifier.get(dust, AntimonyTrioxide))
                .EUt(1980)
                .duration(300)
                .blastFurnaceTemp(4500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, AntimonyTrioxide)
                .fluidInputs(HydrofluoricAcid.getFluid(6000))
                .outputs(AntimonyTrifluoride.getItemStack(2))
                .fluidOutputs(Water.getFluid(3000))
                .EUt(7680)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(AntimonyTrifluoride.getItemStack())
                .fluidInputs(Fluorine.getFluid(2000))
                .fluidOutputs(AntimonyPentafluoride.getFluid(1000))
                .EUt(7680)
                .duration(100)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(AntimonyPentafluoride.getFluid(1000))
                .fluidInputs(HydrofluoricAcid.getFluid(2000))
                .fluidOutputs(FluoroantimonicAcid.getFluid(1000))
                .fluidOutputs(Hydrogen.getFluid(2000))
                .fluidOutputs(Fluorine.getFluid(1000))
                .EUt(7680)
                .duration(200)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(NaquadricSolution.getFluid(1000))
                .fluidInputs(FluoroantimonicAcid.getFluid(1000))
                .outputs(AntimonyTrifluoride.getItemStack())
                .fluidOutputs(FluoronaquadricAcid.getFluid(2000))
                .EUt(7680)
                .duration(300)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(EnrichedNaquadricSolution.getFluid(1000))
                .fluidInputs(FluoroantimonicAcid.getFluid(1000))
                .outputs(AntimonyTrifluoride.getItemStack())
                .fluidOutputs(EnrichedFluoronaquadricAcid.getFluid(1000))
                .EUt(7680)
                .duration(300)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(NaquadriaticSolution.getFluid(1000))
                .fluidInputs(FluoroantimonicAcid.getFluid(1000))
                .outputs(AntimonyTrifluoride.getItemStack())
                .fluidOutputs(FluoronaquadriaticAcid.getFluid(1000))
                .EUt(7680)
                .duration(300)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(FluoronaquadricAcid.getFluid(2000))
                .fluidOutputs(HydrofluoricAcid.getFluid(1000))
                .fluidOutputs(NaquadahDifluoride.getFluid(1000))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(EnrichedFluoronaquadricAcid.getFluid(2000))
                .fluidOutputs(HydrofluoricAcid.getFluid(1000))
                .fluidOutputs(EnrichedNaquadahDifluoride.getFluid(1000))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(FluoronaquadriaticAcid.getFluid(2000))
                .fluidOutputs(HydrofluoricAcid.getFluid(1000))
                .fluidOutputs(NaquadriaDifluoride.getFluid(1000))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .fluidInputs(NaquadahDifluoride.getFluid(1000))
                .input(dust, Indium)
                .outputs(IndiumTrifluoride.getItemStack())
                .outputs(NaquadahConcentrate.getItemStack())
                .EUt(30720)
                .duration(1000)
                .blastFurnaceTemp(4500)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .fluidInputs(EnrichedNaquadahDifluoride.getFluid(1000))
                .input(dust, Indium)
                .outputs(IndiumTrifluoride.getItemStack())
                .outputs(EnrichedNaquadahConcentrate.getItemStack())
                .EUt(30720)
                .duration(1000)
                .blastFurnaceTemp(4500)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .fluidInputs(NaquadriaDifluoride.getFluid(1000))
                .input(dust, Indium)
                .outputs(IndiumTrifluoride.getItemStack())
                .outputs(NaquadriaConcentrate.getItemStack())
                .EUt(30720)
                .duration(1000)
                .blastFurnaceTemp(4500)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Fluorine.getFluid(6000))
                .inputs(NaquadriaConcentrate.getItemStack())
                .fluidOutputs(NaquadriaHexafluoride.getFluid(6000))
                .EUt(7680)
                .duration(1000)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Radon.getFluid(1000))
                .fluidInputs(Fluorine.getFluid(2000))
                .fluidOutputs(RadonDifluoride.getFluid(3000))
                .EUt(7680)
                .duration(800)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(RadonDifluoride.getFluid(1000))
                .fluidInputs(NaquadriaHexafluoride.getFluid(1000))
                .fluidOutputs(RadonNaquadriaoctafluoride.getFluid(2000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Xenon.getFluid(1000))
                .fluidInputs(Oxygen.getFluid(3000))
                .fluidOutputs(XenonTrioxide.getFluid(4000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Caesium)
                .fluidInputs(Fluorine.getFluid(1000))
                .fluidOutputs(CesiumFluoride.getFluid(2000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(CesiumFluoride.getFluid(1000))
                .fluidInputs(XenonTrioxide.getFluid(1000))
                .fluidOutputs(CesiumXenontrioxideFluoride.getFluid(2000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(CesiumXenontrioxideFluoride.getFluid(1000))
                .fluidInputs(RadonNaquadriaoctafluoride.getFluid(1000))
                .fluidOutputs(RadonTrioxide.getFluid(1000))
                .fluidOutputs(NaquadriaCesiumXenonNonfluoride.getFluid(1000))
                .EUt(7680)
                .duration(1200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(NitricOxide.getFluid(1000))
                .fluidInputs(Fluorine.getFluid(1000))
                .fluidOutputs(NitrosylFluoride.getFluid(2000))
                .EUt(1920)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(NitrosylFluoride.getFluid(1000))
                .fluidInputs(NaquadriaCesiumXenonNonfluoride.getFluid(1000))
                .fluidOutputs(NitrosoniumOctafluoroxenate.getFluid(1000))
                .fluidOutputs(NaquadriaCesiumfluoride.getFluid(1000))
                .EUt(7680)
                .duration(750)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(NaquadriaCesiumfluoride.getFluid(6000))
                .outputs(OreDictUnifier.get(dust, Naquadria))
                .fluidOutputs(Fluorine.getFluid(2500))
                .fluidOutputs(Caesium.getFluid(2500))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(RadonTrioxide.getFluid(4000))
                .fluidOutputs(Radon.getFluid(1000))
                .fluidOutputs(Oxygen.getFluid(3000))
                .EUt(1920)
                .duration(400)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(NitrosoniumOctafluoroxenate.getFluid(13000))
                .fluidOutputs(Fluorine.getFluid(8000))
                .fluidOutputs(Xenon.getFluid(1000))
                .fluidOutputs(NitricOxide.getFluid(2000))
                .EUt(1920)
                .duration(500)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(EnrichedNaquadahConcentrate.getItemStack())
                .fluidInputs(Fluorine.getFluid(6000))
                .fluidOutputs(EnrichedNaquadahhexafluoride.getFluid(6000))
                .EUt(7680)
                .duration(650)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(EnrichedNaquadahhexafluoride.getFluid(1000))
                .fluidInputs(Xenon.getFluid(1000))
                .fluidOutputs(EnrichedXenonHexafluoronaquadate.getFluid(2000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(ChloroauricAcid.getFluid(1000))
                .fluidInputs(Chlorine.getFluid(1000))
                .fluidOutputs(AuricChloride.getFluid(2000))
                .EUt(1920)
                .duration(800)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Bromine.getFluid(1000))
                .fluidInputs(Fluorine.getFluid(3000))
                .fluidOutputs(BromineTrifluoride.getFluid(4000))
                .EUt(1920)
                .duration(250)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(BromineTrifluoride.getFluid(1000))
                .fluidInputs(AuricChloride.getFluid(1000))
                .outputs(AuricFluoride.getItemStack())
                .fluidOutputs(Bromine.getFluid(500))
                .fluidOutputs(Chlorine.getFluid(1500))
                .EUt(1920)
                .duration(300)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(FluoroantimonicAcid.getFluid(6000))
                .inputs(AuricFluoride.getItemStack(6))
                .fluidInputs(EnrichedXenonHexafluoronaquadate.getFluid(6000))
                .outputs(OreDictUnifier.get(dust, NaquadahEnriched))
                .fluidOutputs(XenoauricFluoroantimonicAcid.getFluid(12000))
                .EUt(7680)
                .duration(650)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(XenoauricFluoroantimonicAcid.getFluid(29000))
                .outputs(OreDictUnifier.get(dust, Gold))
                .fluidOutputs(Xenon.getFluid(2000))
                .outputs(OreDictUnifier.get(dust, Antimony, 4))
                .fluidOutputs(Fluorine.getFluid(22000))
                .EUt(1920)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(HydrofluoricAcid.getFluid(1000))
                .input(dust, PotassiumMetabisulfite)
                .inputs(NaquadahConcentrate.getItemStack())
                .fluidOutputs(Water.getFluid(1000))
                .outputs(OreDictUnifier.get(dust, PotassiumFluoride))
                .fluidOutputs(NaquadahSulfate.getFluid(1000))
                .EUt(7980)
                .duration(500)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(NaquadahSulfate.getFluid(1000))
                .fluidInputs(Hydrogen.getFluid(1000))
                .fluidOutputs(SulfuricAcid.getFluid(2000))
                .outputs(OreDictUnifier.get(dust, Naquadah))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(IndiumTrifluoride.getItemStack())
                .fluidInputs(NitricAcid.getFluid(1000))
                .outputs(IndiumTrioxide.getItemStack())
                .fluidOutputs(Oxygen.getFluid(500))
                .fluidOutputs(Nitrogen.getFluid(500))
                .EUt(1920)
                .duration(200)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .inputs(IndiumTrioxide.getItemStack())
                .input(dust, Carbon)
                .outputs(OreDictUnifier.get(dust, Indium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(800)
                .blastFurnaceTemp(4500)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Ammonia.getFluid(1000))
                .fluidInputs(NitricAcid.getFluid(1000))
                .fluidOutputs(AmmoniaNitrate.getFluid(2000))
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Naquadah)
                .fluidInputs(AmmoniaNitrate.getFluid(1000))
                .EUt(7680)
                .duration(200)
                .fluidOutputs(NaquadahSolution.getFluid(1000))
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(NaquadahSolution.getFluid(2000))
                .fluidOutputs(ClearNaquadahLiquid.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, PlatinumRawPowder, 5))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride, 3))
                .outputs(OreDictUnifier.get(dustTiny, Naquadah, 1))
                .EUt(7680)
                .duration(150)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(ClearNaquadahLiquid.getFluid(1000))
                .fluidOutputs(ComplicatedNaquadahGas.getFluid(60))
                .fluidOutputs(ComplicatedLightNaquadah.getFluid(180))
                .fluidOutputs(ComplicatedMediumNaquadah.getFluid(320))
                .fluidOutputs(ComplicatedHeavyNaquadah.getFluid(440))
                .EUt(7680)
                .duration(1200)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ComplicatedNaquadahGas.getFluid(2000))
                .fluidOutputs(NaquadahGas.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ComplicatedHeavyNaquadah.getFluid(2000))
                .fluidOutputs(HeavyNaquadah.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ComplicatedLightNaquadah.getFluid(2000))
                .fluidOutputs(LightNaquadah.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ComplicatedMediumNaquadah.getFluid(2000))
                .fluidOutputs(MediumNaquadah.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        CRACKING_RECIPES.recipeBuilder()
                .fluidInputs(MediumNaquadah.getFluid(1000))
                .fluidInputs(Fluorine.getFluid(200))
                .fluidOutputs(FlCrackedMediumNaquadah.getFluid(1000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CRACKING_RECIPES.recipeBuilder()
                .fluidInputs(LightNaquadah.getFluid(1000))
                .fluidInputs(Fluorine.getFluid(400))
                .fluidOutputs(FlCrackedLightNaquadah.getFluid(1000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CRACKING_RECIPES.recipeBuilder()
                .fluidInputs(HeavyNaquadah.getFluid(1000))
                .fluidInputs(Fluorine.getFluid(600))
                .fluidOutputs(FlCrackedHeavyNaquadah.getFluid(1000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(FlCrackedLightNaquadah.getFluid(1000))
                .fluidOutputs(NaquadahGas.getFluid(350))
                .fluidOutputs(LightNaquadahFuel.getFluid(400))
                .fluidOutputs(MediumNaquadahFuel.getFluid(150))
                .fluidOutputs(HeavyNaquadahFuel.getFluid(50))
                .fluidOutputs(Fluorine.getFluid(50))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(FlCrackedMediumNaquadah.getFluid(1000))
                .fluidOutputs(NaquadahGas.getFluid(150))
                .fluidOutputs(LightNaquadahFuel.getFluid(200))
                .fluidOutputs(MediumNaquadahFuel.getFluid(400))
                .fluidOutputs(HeavyNaquadahFuel.getFluid(100))
                .fluidOutputs(Fluorine.getFluid(150))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(FlCrackedHeavyNaquadah.getFluid(1000))
                .fluidOutputs(NaquadahGas.getFluid(50))
                .fluidOutputs(LightNaquadahFuel.getFluid(100))
                .fluidOutputs(MediumNaquadahFuel.getFluid(200))
                .fluidOutputs(HeavyNaquadahFuel.getFluid(400))
                .fluidOutputs(Fluorine.getFluid(250))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Copper)
                .fluidInputs(SulfuricAcid.getFluid(1000))
                .fluidOutputs(CopperSulfateSolution.getFluid(1000))
                .EUt(480)
                .duration(300)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(CopperSulfateSolution.getFluid(900))
                .fluidInputs(NaquadahGas.getFluid(100))
                .input(dust, NaquadahEnriched)
                .fluidOutputs(ENaquadahSolution.getFluid(1000))
                .EUt(7680)
                .duration(200)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ENaquadahSolution.getFluid(2000))
                .outputs(OreDictUnifier.get(dustTiny, PlatinumRawPowder))
                .fluidOutputs(OsmiumSolution.getFluid(350))
                .outputs(OreDictUnifier.get(dustTiny, NaquadahEnriched))
                .fluidOutputs(ClearENaquadahLiquid.getFluid(1000))
                .EUt(7680)
                .duration(200)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(ClearENaquadahLiquid.getFluid(1000))
                .fluidOutputs(ComplicatedNaquadahGas.getFluid(60))
                .fluidOutputs(ComplicatedLightENaquadah.getFluid(180))
                .fluidOutputs(ComplicatedMediumENaquadah.getFluid(320))
                .fluidOutputs(ComplicatedHeavyENaquadah.getFluid(440))
                .EUt(7680)
                .duration(1200)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ComplicatedHeavyENaquadah.getFluid(2000))
                .fluidOutputs(HeavyENaquadah.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, Naquadria))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride, 2))
                .fluidOutputs(OsmiumSolution.getFluid(350))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ComplicatedLightENaquadah.getFluid(2000))
                .fluidOutputs(LightENaquadah.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, Naquadria))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride, 2))
                .fluidOutputs(OsmiumSolution.getFluid(350))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ComplicatedMediumENaquadah.getFluid(2000))
                .fluidOutputs(MediumENaquadah.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, Naquadria))
                .outputs(OreDictUnifier.get(dustTiny, IridiumChloride, 2))
                .fluidOutputs(OsmiumSolution.getFluid(350))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        CRACKING_RECIPES.recipeBuilder()
                .fluidInputs(MediumENaquadah.getFluid(1000))
                .fluidInputs(Radon.getFluid(200))
                .fluidOutputs(RnCrackedMediumENaquadah.getFluid(1000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CRACKING_RECIPES.recipeBuilder()
                .fluidInputs(LightENaquadah.getFluid(1000))
                .fluidInputs(Radon.getFluid(400))
                .fluidOutputs(RnCrackedLighteNaquadah.getFluid(1000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        CRACKING_RECIPES.recipeBuilder()
                .fluidInputs(HeavyENaquadah.getFluid(1000))
                .fluidInputs(Radon.getFluid(600))
                .fluidOutputs(RnCrackedHeavyENaquadah.getFluid(1000))
                .EUt(7680)
                .duration(500)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(RnCrackedLighteNaquadah.getFluid(1000))
                .fluidOutputs(NaquadahGas.getFluid(350))
                .fluidOutputs(LightENaquadahFuel.getFluid(400))
                .fluidOutputs(MediumENaquadahFuel.getFluid(150))
                .fluidOutputs(HeavyENaquadahFuel.getFluid(50))
                .fluidOutputs(Radon.getFluid(50))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(RnCrackedMediumENaquadah.getFluid(1000))
                .fluidOutputs(NaquadahGas.getFluid(150))
                .fluidOutputs(LightENaquadahFuel.getFluid(200))
                .fluidOutputs(MediumENaquadahFuel.getFluid(400))
                .fluidOutputs(HeavyENaquadahFuel.getFluid(100))
                .fluidOutputs(Radon.getFluid(150))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();
        DISTILLATION_RECIPES.recipeBuilder()
                .fluidInputs(RnCrackedHeavyENaquadah.getFluid(1000))
                .fluidOutputs(NaquadahGas.getFluid(50))
                .fluidOutputs(LightENaquadahFuel.getFluid(100))
                .fluidOutputs(MediumENaquadahFuel.getFluid(200))
                .fluidOutputs(HeavyENaquadahFuel.getFluid(400))
                .fluidOutputs(Radon.getFluid(250))
                .EUt(7680)
                .duration(600)
                .buildAndRegister();

        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .input(dust, Naquadria)
                .fluidInputs(NitrogenDioxide.getFluid(500))
                .fluidInputs(SulfuricAcid.getFluid(500))
                .fluidOutputs(NaquadriaSolution.getFluid(1000))
                .outputs(OreDictUnifier.get(dustTiny, Lutetium))
                .outputs(OreDictUnifier.get(dustTiny, Uranium))
                .outputs(OreDictUnifier.get(dustTiny, NaquadahEnriched))
                .outputs(OreDictUnifier.get(dustTiny, Plutonium))
                .EUt(7680)
                .duration(300)
                .buildAndRegister();
        LARGE_MIXER_RECIPES.recipeBuilder()
                .fluidInputs(LightNaquadahFuel.getFluid(500))
                .fluidInputs(LightENaquadahFuel.getFluid(300))
                .fluidInputs(NaquadriaSolution.getFluid(200))
                .input(dust, Rutherfordium)
                .fluidInputs(Plutonium244Isotope.getMaterial().getFluid(144))
                .fluidOutputs(HyperFuelI.getFluid(2000))
                .EUt(7680)
                .duration(200)
                .buildAndRegister();
        LARGE_MIXER_RECIPES.recipeBuilder()
                .fluidInputs(MediumNaquadahFuel.getFluid(400))
                .fluidInputs(MediumENaquadahFuel.getFluid(350))
                .fluidInputs(NaquadriaSolution.getFluid(250))
                .input(dust, Dubnium)
                .fluidInputs(Curium250.getMaterial().getFluid(144))
                .fluidOutputs(HyperFuelII.getFluid(2000))
                .EUt(7680)
                .duration(200)
                .buildAndRegister();
        LARGE_MIXER_RECIPES.recipeBuilder()
                .fluidInputs(HeavyNaquadahFuel.getFluid(300))
                .fluidInputs(HeavyENaquadahFuel.getFluid(400))
                .fluidInputs(NaquadriaSolution.getFluid(300))
                .input(dust, Neutronium)
                .fluidInputs(Californium256.getMaterial().getFluid(144))
                .fluidOutputs(HyperFuelIII.getFluid(2000))
                .EUt(7680)
                .duration(200)
                .buildAndRegister();
    }
}
