package gregicadditions.recipes.chain;

import gregtech.api.unification.OreDictUnifier;

import static gregicadditions.GAMaterials.*;
import static gregicadditions.recipes.GARecipeMaps.*;
import static gregtech.api.recipes.RecipeMaps.*;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.ore.OrePrefix.dust;
import static gregtech.api.unification.ore.OrePrefix.dustTiny;

public class REEChain {
    public static void init() {
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(SaltWater.getFluid(1500))
                .fluidInputs(Chlorine.getFluid(1000))
                .fluidInputs(SulfuricAcid.getFluid(500))
                .fluidOutputs(AcidicSaltWater.getFluid(3000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();

        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(AcidicSaltWater.getFluid(6000))
                .outputs(OreDictUnifier.get(dust, Salt, 4))
                .outputs(OreDictUnifier.get(dust, SodiumSulfate))
                .fluidOutputs(SulfuricBromineSolution.getFluid(3000))
                .fluidOutputs(DebrominatedWater.getFluid(3000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(SulfuricBromineSolution.getFluid(1500))
                .fluidInputs(Steam.getFluid(1500))
                .fluidOutputs(HotVapourMixture.getFluid(3000))
                .EUt(480)
                .duration(150)
                .buildAndRegister();

        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(HotVapourMixture.getFluid(3000))
                .fluidOutputs(DilutedHydrochloricAcid.getFluid(2000))
                .fluidOutputs(DampBromine.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();

        CHEMICAL_DEHYDRATOR_RECIPES.recipeBuilder()
                .fluidInputs(DampBromine.getFluid(2000))
                .fluidOutputs(Bromine.getFluid(1000))
                .EUt(480)
                .duration(500)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(CarbonMonoxde.getFluid(1000))
                .fluidInputs(Propene.getFluid(1000))
                .fluidInputs(Hydrogen.getFluid(2000))
                .fluidOutputs(Butyraldehyde.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Butyraldehyde.getFluid(2000))
                .fluidInputs(Hydrogen.getFluid(4000))
                .fluidOutputs(Ethylhexanol.getFluid(3000))
                .fluidOutputs(Water.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Ethylhexanol.getFluid(6000))
                .input(dust, PhosphorousPentoxide)
                .fluidOutputs(DiethylhexylPhosphoricAcid.getFluid(2000))
                .fluidOutputs(Butene.getFluid(4000))
                .fluidOutputs(Water.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        MIXER_RECIPES.recipeBuilder()
                .input(dust, RareEarth)
                .input(dust, SodiumHydroxide)
                .fluidInputs(Water.getFluid(1000))
                .fluidOutputs(RareEarthHydroxidesSolution.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(HydrochloricAcid.getFluid(1000))
                .fluidInputs(RareEarthHydroxidesSolution.getFluid(1000))
                .outputs(ThUSludge.getItemStack())
                .fluidOutputs(RareEarthChloridesSolution.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(RareEarthChloridesSolution.getFluid(1000))
                .fluidInputs(DiethylhexylPhosphoricAcid.getFluid(1000))
                .outputs(OreDictUnifier.get(dust, SodiumHydroxide))
                .fluidOutputs(LaNdOxidesSolution.getFluid(250))
                .fluidOutputs(SmGdOxidesSolution.getFluid(250))
                .fluidOutputs(TbHoOxidesSolution.getFluid(250))
                .fluidOutputs(ErLuOxidesSolution.getFluid(250))
                .fluidOutputs(DilutedHydrochloricAcid.getFluid(2000))
                .EUt(480)
                .duration(600)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(LaNdOxidesSolution.getFluid(4000))
                .chancedOutput(LanthanumOxide.getItemStack(), 4300, 275)
                .chancedOutput(PraseodymiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(NeodymiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(CeriumOxide.getItemStack(), 4300, 275)
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(SmGdOxidesSolution.getFluid(4000))
                .chancedOutput(ScandiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(EuropiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(GadoliniumOxide.getItemStack(), 4300, 275)
                .chancedOutput(SamariumOxide.getItemStack(), 4300, 275)
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(TbHoOxidesSolution.getFluid(4000))
                .chancedOutput(OreDictUnifier.get(dust, YttriumOxide), 4300, 275)
                .chancedOutput(TerbiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(DysprosiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(HolmiumOxide.getItemStack(), 4300, 275)
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ErLuOxidesSolution.getFluid(4000))
                .chancedOutput(ErbiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(ThuliumOxide.getItemStack(), 4300, 275)
                .chancedOutput(YtterbiumOxide.getItemStack(), 4300, 275)
                .chancedOutput(LutetiumOxide.getItemStack(), 4300, 275)
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(LanthanumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Lanthanum,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(PraseodymiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Praseodymium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(NeodymiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Neodymium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(CeriumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Cerium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(ScandiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Scandium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(EuropiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Europium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(GadoliniumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Gadolinium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon, 3)
                .inputs(SamariumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Samarium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .input(dust, YttriumOxide,2)
                .outputs(OreDictUnifier.get(dust, Yttrium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .inputs(TerbiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Terbium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .inputs(DysprosiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Dysprosium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .inputs(HolmiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Holmium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .inputs(ErbiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Erbium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .inputs(ThuliumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Thulium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .inputs(YtterbiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Ytterbium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon,3)
                .inputs(LutetiumOxide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Lutetium,4))
                .fluidOutputs(CarbonDioxide.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        CENTRIFUGE_RECIPES.recipeBuilder()
                .inputs(ThUSludge.getItemStack(2))
                .chancedOutput(OreDictUnifier.get(dustTiny, Thorium), 2000, 150)
                .chancedOutput(OreDictUnifier.get(dustTiny, UraniumRadioactive.getMaterial()), 2000, 150)
                .EUt(480)
                .duration(500)
                .buildAndRegister();
    }
}
