package gregicadditions.recipes.chain;

import gregtech.api.unification.OreDictUnifier;

import static gregicadditions.GAMaterials.*;
import static gregicadditions.recipes.GARecipeMaps.CHEMICAL_DEHYDRATOR_RECIPES;
import static gregicadditions.recipes.GARecipeMaps.LARGE_CENTRIFUGE_RECIPES;
import static gregtech.api.recipes.RecipeMaps.*;
import static gregtech.api.recipes.RecipeMaps.ELECTROLYZER_RECIPES;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.ore.OrePrefix.dust;

public class REEChain {
    public static void init() {
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(SaltWater.getFluid(1000))
                .fluidInputs(Chlorine.getFluid(100))
                .fluidInputs(SulfuricAcid.getFluid(100))
                .fluidOutputs(AcidicSaltWater.getFluid(1200))
                .EUt(480)
                .duration(200)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(AcidicSaltWater.getFluid(1000))
                .fluidInputs(SulfurDioxide.getFluid(500))
                .fluidInputs(Water.getFluid(500))
                .fluidOutputs(SulfuricBromineSolution.getFluid(2000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(SulfuricBromineSolution.getFluid(1000))
                .fluidInputs(Steam.getFluid(500))
                .fluidOutputs(HotVapourMixture.getFluid(1500))
                .EUt(480)
                .duration(150)
                .buildAndRegister();

        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(HotVapourMixture.getFluid(1000))
                .fluidOutputs(DilutedHydrochloricAcid.getFluid(1000))
                .fluidOutputs(DampBromine.getFluid(500))
                .EUt(480)
                .duration(200)
                .buildAndRegister();

        CHEMICAL_DEHYDRATOR_RECIPES.recipeBuilder()
                .fluidInputs(DampBromine.getFluid(1000))
                .fluidOutputs(Bromine.getFluid(500))
                .EUt(480)
                .duration(500)
                .buildAndRegister();

        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(CarbonMonoxde.getFluid(1000))
                .fluidInputs(Propene.getFluid(1000))
                .fluidInputs(Hydrogen.getFluid(1000))
                .fluidOutputs(Butyraldehyde.getFluid(3000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Butyraldehyde.getFluid(1000))
                .fluidInputs(CarbonMonoxde.getFluid(1000))
                .fluidInputs(Hydrogen.getFluid(1000))
                .fluidOutputs(Ethylhexanol.getFluid(3000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Ethylhexanol.getFluid(1000))
                .input(dust, PhosphorousPentoxide)
                .fluidOutputs(DiethylhexylPhosphoricAcid.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, RareEarth)
                .fluidInputs(SodiumHydroxideSolution.getFluid(1000))
                .fluidOutputs(RareEarthHydroxidesSolution.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        MIXER_RECIPES.recipeBuilder()
                .input(dust, SodiumHydroxide)
                .fluidInputs(Water.getFluid(1000))
                .fluidOutputs(SodiumHydroxideSolution.getFluid(2000))
                .EUt(120)
                .duration(400)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(HydrochloricAcid.getFluid(1000))
                .fluidInputs(RareEarthHydroxidesSolution.getFluid(1000))
                .outputs(ThUSludge.getItemStack())
                .fluidOutputs(RareEarthChloridesSolution.getFluid(1000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(RareEarthChloridesSolution.getFluid(1000))
                .fluidInputs(DiethylhexylPhosphoricAcid.getFluid(1000))
                .fluidOutputs(LaNdOxidesSolution.getFluid(250))
                .fluidOutputs(SmGdOxidesSolution.getFluid(250))
                .fluidOutputs(TbHoOxidesSolution.getFluid(250))
                .fluidOutputs(ErLuOxidesSolution.getFluid(250))
                .EUt(480)
                .duration(600)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(LaNdOxidesSolution.getFluid(1000))
                .outputs(LanthanumOxide.getItemStack())
                .outputs(PraseodymiumOxide.getItemStack())
                .outputs(NeodymiumOxide.getItemStack())
                .outputs(CeriumOxide.getItemStack())
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(SmGdOxidesSolution.getFluid(1000))
                .outputs(ScandiumOxide.getItemStack())
                .outputs(EuropiumOxide.getItemStack())
                .outputs(GadoliniumOxide.getItemStack())
                .outputs(SamariumOxide.getItemStack())
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(TbHoOxidesSolution.getFluid(1000))
                .outputs(OreDictUnifier.get(dust, YttriumOxide))
                .outputs(TerbiumOxide.getItemStack())
                .outputs(DysprosiumOxide.getItemStack())
                .outputs(HolmiumOxide.getItemStack())
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ErLuOxidesSolution.getFluid(1000))
                .outputs(ErbiumOxide.getItemStack())
                .outputs(ThuliumOxide.getItemStack())
                .outputs(YtterbiumOxide.getItemStack())
                .outputs(LutetiumOxide.getItemStack())
                .EUt(480)
                .duration(250)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(LanthanumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Lanthanum))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(PraseodymiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Praseodymium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(NeodymiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Neodymium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(CeriumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Cerium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(ScandiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Scandium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(EuropiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Europium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(GadoliniumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Gadolinium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(SamariumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Samarium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .input(dust, YttriumOxide)
                .outputs(OreDictUnifier.get(dust, Yttrium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(TerbiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Terbium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(DysprosiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Dysprosium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(HolmiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Holmium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(ErbiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Erbium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(ThuliumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Thulium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(YtterbiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Ytterbium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .blastFurnaceTemp(2500)
                .input(dust, Carbon)
                .inputs(LutetiumOxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Lutetium))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();

        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(TrisodiumPhosphate.getFluid(4000))
                .outputs(OreDictUnifier.get(dust, Sodium, 3))
                .outputs(OreDictUnifier.get(dust, Phosphate))
                .EUt(120)
                .duration(400)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .inputs(ThUSludge.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Thorium))
                .outputs(OreDictUnifier.get(dust, Uranium))
                .EUt(480)
                .duration(500)
                .buildAndRegister();
    }
}
