package gregicadditions.recipes.chain;

import gregtech.api.unification.OreDictUnifier;

import static gregicadditions.GAMaterials.*;
import static gregicadditions.item.GAMetaItems.*;
import static gregicadditions.recipes.GARecipeMaps.*;
import static gregtech.api.recipes.RecipeMaps.*;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.ore.OrePrefix.dust;

public class RheniumChain {
    public static void init() {
        // Molybdenite MUST NOT be producable from it's components!
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Methane.getFluid(8000))
                .fluidInputs(Ammonia.getFluid(8000))
                .fluidInputs(Oxygen.getFluid(24000))
                .fluidOutputs(HydrogenCyanide.getFluid(8000))
                .fluidOutputs(Water.getFluid(24000))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(HydrogenCyanide.getFluid(8000))
                .fluidInputs(Oxygen.getFluid(4000))
                .input(dust, Sodium, 8)
                .fluidOutputs(SodiumCyanide.getFluid(8000))
                .fluidOutputs(Water.getFluid(4000))
                .EUt(491520)
                .duration(50)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Molybdenite, 4)
                .fluidInputs(SodiumCyanide.getFluid(2000))
                .fluidOutputs(GoldCyanide.getFluid(1000))
                .outputs(GoldDepleteMolybdenite.getItemStack(4))
                .EUt(122880)
                .duration(100)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(GoldCyanide.getFluid(5000))
                .outputs(OreDictUnifier.get(dust, Gold))
                .outputs(OreDictUnifier.get(dust, Sodium, 5))
                .outputs(OreDictUnifier.get(dust, Carbon, 5))
                .fluidOutputs(SodiumCyanide.getFluid(5000))
                .fluidOutputs(Nitrogen.getFluid(5000))
                .EUt(7680)
                .duration(150)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GoldDepleteMolybdenite.getItemStack())
                .fluidInputs(IronChloride.getFluid(500))
                .outputs(MolybdenumConcentrate.getItemStack())
                .fluidOutputs(ChlorideLeachedSolution.getFluid(500))
                .EUt(491520)
                .duration(10)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .fluidInputs(ChlorideLeachedSolution.getFluid(8000))
                .outputs(OreDictUnifier.get(dust, CalciumChloride, 3))
                .outputs(CopperChloride.getItemStack(2))
                .outputs(LeadChloride.getItemStack(3))
                .outputs(BismuthChloride.getItemStack(4))
                .fluidOutputs(Iron2Chloride.getFluid(8000))
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Iron2Chloride.getFluid(1000))
                .fluidInputs(Chlorine.getFluid(1000))
                .fluidOutputs(IronChloride.getFluid(1000))
                .EUt(120)
                .duration(150)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .inputs(CopperChloride.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Copper))
                .fluidOutputs(Chlorine.getFluid(2000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .inputs(LeadChloride.getItemStack(3))
                .outputs(OreDictUnifier.get(dust, Lead))
                .fluidOutputs(Chlorine.getFluid(2000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .inputs(BismuthChloride.getItemStack(4))
                .outputs(OreDictUnifier.get(dust, Bismuth))
                .fluidOutputs(Chlorine.getFluid(3000))
                .EUt(480)
                .duration(100)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .inputs(MolybdenumConcentrate.getItemStack(2))
                .fluidInputs(Oxygen.getFluid(7250))
                .blastFurnaceTemp(8550)
                .EUt(491520)
                .duration(50)
                .fluidOutputs(MolybdenumFlue.getFluid(3000))
                .outputs(MolybdenumTrioxide.getItemStack())
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .fluidInputs(Hydrogen.getFluid(6000))
                .inputs(MolybdenumTrioxide.getItemStack())
                .outputs(OreDictUnifier.get(dust, Molybdenum))
                .fluidOutputs(Water.getFluid(3000))
                .blastFurnaceTemp(1000)
                .EUt(480)
                .duration(200)
                .buildAndRegister();
        MIXER_RECIPES.recipeBuilder()
                .fluidInputs(MolybdenumFlue.getFluid(3000))
                .fluidInputs(Water.getFluid(250))
                .fluidOutputs(RheniumSulfuricSolution.getFluid(3000))
                .EUt(491520)
                .duration(30)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(RheniumSulfuricSolution.getFluid(3000))
                .fluidInputs(Ammonia.getFluid(500))
                .fluidOutputs(SulfurDioxide.getFluid(3000))
                .fluidOutputs(AmmoniumPerrhenate.getFluid(500))
                .EUt(491520)
                .duration(25)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(AmmoniumPerrhenate.getFluid(1000))
                .fluidInputs(Hydrogen.getFluid(7000))
                .outputs(OreDictUnifier.get(dust, Rhenium))
                .fluidOutputs(Ammonia.getFluid(1000))
                .fluidOutputs(Water.getFluid(4000))
                .EUt(491520)
                .duration(20)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Mercury.getFluid(1000))
                .fluidInputs(AceticAcid.getFluid(2000))
                .outputs(MercuryAcetate.getItemStack())
                .fluidOutputs(Hydrogen.getFluid(2000))
                .EUt(125000)
                .duration(90)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(EthyleneOxide.getFluid(1000))
                .fluidInputs(Methylamine.getFluid(1000))
                .fluidOutputs(Methylethanolamine.getFluid(1000))
                .EUt(125000)
                .duration(90)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .inputs(CalciumCarbide.getItemStack())
                .fluidInputs(Nitrogen.getFluid(2000))
                .outputs(CalciumCyanamide.getItemStack(4))
                .outputs(OreDictUnifier.get(dust, Carbon))
                .blastFurnaceTemp(2000)
                .EUt(4800)
                .duration(90)
                .buildAndRegister();
        CHEMICAL_PLANT_RECIPES.recipeBuilder()
                .fluidInputs(HydrochloricAcid.getFluid(2000))
                .fluidInputs(Methylethanolamine.getFluid(1000))
                .fluidInputs(Oxygen.getFluid(1000))
                .inputs(CalciumCyanamide.getItemStack(4))
                .fluidOutputs(Methylguanidine.getFluid(1000))
                .fluidOutputs(AceticAcid.getFluid(1000))
                .outputs(OreDictUnifier.get(dust, CalciumChloride, 3))
                .notConsumable(dust,Palladium)
                .notConsumable(MercuryAcetate.getItemStack())
                .EUt(250000)
                .duration(40)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Methylguanidine.getFluid(1000))
                .fluidInputs(NitrationMixture.getFluid(2000))
                .fluidInputs(HydrochloricAcid.getFluid(1000))
                .inputs(SodiumNitrite.getItemStack())
                .fluidOutputs(DilutedSulfuricAcid.getFluid(2000))
                .fluidOutputs(Methylnitronitrosoguanidine.getFluid(1000))
                .outputs(OreDictUnifier.get(dust, Salt, 2))
                .EUt(250000)
                .duration(40)
                .buildAndRegister();
        BIO_REACTOR_RECIPES.recipeBuilder()
                .inputs(Glucose.getItemStack())
                .inputs(SelectivelyMutatedCupravidiusNecator.getItemStack())
                .fluidInputs(Ammonia.getFluid(10))
                .fluidOutputs(IsoamylAlcohol.getFluid(1000))
                .EUt(491520)
                .duration(20)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Oct1ene.getFluid(1000))
                .fluidInputs(Water.getFluid(1000))
                .fluidInputs(PhosphoricAcid.getFluid(10))
                .fluidOutputs(Octanol.getFluid(1000))
                .notConsumable(PalladiumLoadedRutileNanoparticles.getItemStack())
                .notConsumable(UVA_HALIDE_LAMP.getStackForm())
                .EUt(150000)
                .duration(90)
                .buildAndRegister();
        BIO_REACTOR_RECIPES.recipeBuilder()
                .inputs(CupriavidusNecator.getItemStack(2))
                .notConsumable(UVA_HALIDE_LAMP)
                .fluidInputs(Methylnitronitrosoguanidine.getFluid(250))
                .outputs(SelectivelyMutatedCupravidiusNecator.getItemStack())
                .EUt(491520)
                .duration(20)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Octanol.getFluid(3000))
                .fluidInputs(Ammonia.getFluid(1000))
                .fluidOutputs(Water.getFluid(3000))
                .fluidOutputs(Trioctylamine.getFluid(1000))
                .EUt(125000)
                .duration(90)
                .buildAndRegister();
        LARGE_MIXER_RECIPES.recipeBuilder()
                .fluidInputs(Kerosene.getFluid(2000))
                .fluidInputs(Trioctylamine.getFluid(500))
                .fluidInputs(Octanol.getFluid(250))
                .fluidInputs(MethylIsobutylKetone.getFluid(500))
                .fluidInputs(AceticAcid.getFluid(375))
                .fluidInputs(IsoamylAlcohol.getFluid(375))
                .fluidOutputs(RheniumSeparationMixture.getFluid(4000))
                .EUt(125000)
                .duration(90)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .input(dust,PlatinumSaltCrude)
                .fluidInputs(RheniumSeparationMixture.getFluid(200))
                .outputs(OreDictUnifier.get(dust, PlatinumSaltRefined))
                .chancedOutput(OreDictUnifier.get(dust,PlatinumSaltRefined),2000,0)
                .fluidOutputs(RheniumScrubbedSolution.getFluid(200))
                .EUt(50000)
                .duration(50)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .inputs(LeachedColumbite.getItemStack())
                .fluidInputs(RheniumSeparationMixture.getFluid(200))
                .outputs(PurifiedColumbite.getItemStack())
                .fluidOutputs(RheniumScrubbedSolution.getFluid(200))
                .EUt(50000)
                .duration(50)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .inputs(LeachedPyrochlore.getItemStack())
                .fluidInputs(RheniumSeparationMixture.getFluid(200))
                .outputs(PurifiedPyrochlore.getItemStack())
                .fluidOutputs(RheniumScrubbedSolution.getFluid(200))
                .EUt(50000)
                .duration(50)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(PurifiedColumbite.getItemStack())
                .fluidInputs(HydrofluoricAcid.getFluid(5000))
                .fluidOutputs(FluoroniobicAcid.getFluid(1000))
                .EUt(1230)
                .duration(180)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(PurifiedPyrochlore.getItemStack())
                .fluidInputs(HydrofluoricAcid.getFluid(5000))
                .fluidOutputs(FluoroniobicAcid.getFluid(1000))
                .EUt(1230)
                .duration(180)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(RheniumScrubbedSolution.getFluid(1000))
                .fluidInputs(Ammonia.getFluid(3000))
                .fluidInputs(SulfuricAcid.getFluid(1000))
                .fluidOutputs(AmmoniumSulfate.getFluid(1000))
                .fluidOutputs(AmmoniumPerrhenate.getFluid(1000))
                .EUt(491520)
                .duration(25)
                .buildAndRegister();

    }
}
