package gregicadditions;

import com.google.common.collect.ImmutableList;
import gregicadditions.materials.*;
import gregtech.api.unification.material.IMaterialHandler;
import gregtech.api.unification.material.Material;
import gregtech.api.unification.material.info.MaterialFlag;
import gregtech.api.unification.material.info.MaterialIconSet;
import gregtech.api.unification.material.properties.WireProperties;
import gregtech.api.unification.ore.OrePrefix;
import gregtech.api.unification.stack.MaterialStack;
import net.minecraft.util.text.TextFormatting;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static com.google.common.collect.ImmutableList.of;
import static gregtech.api.unification.material.Materials.*;
import static gregicadditions.GAEnums.EnumIonsGroups.*;
import static gregtech.api.unification.material.info.MaterialFlags.*;

@IMaterialHandler.RegisterMaterialHandler
public class GAMaterials implements IMaterialHandler {

    public static long DISABLE_REPLICATION = createFlag(47);

    public static long GENERATE_NUCLEAR_COMPOUND = createFlag(48);
    public static long GENERATE_ISOTOPES_COMPOUND = createFlag(49);

    public static long DISABLE_AUTOGENERATED_MIXER_RECIPE = createFlag(50);

    public static final List<MaterialFlag> GA_STD_METAL = new ArrayList<>();
    public static final List<MaterialFlag> GA_EXT2_METAL = new ArrayList<>();
    public static final List<MaterialFlag> GA_CORE_METAL = new ArrayList<>();

    static {
        GA_STD_METAL.add(GENERATE_PLATE);

        GA_EXT2_METAL.addAll(GA_STD_METAL);
        GA_EXT2_METAL.addAll(Arrays.asList(GENERATE_DENSE, GENERATE_ROD, GENERATE_BOLT_SCREW, GENERATE_GEAR, GENERATE_FOIL, GENERATE_FINE_WIRE, GENERATE_LONG_ROD));

        GA_CORE_METAL.addAll(GA_EXT2_METAL);
        GA_CORE_METAL.addAll(Arrays.asList(GENERATE_RING, GENERATE_FRAME, GENERATE_ROTOR, GENERATE_SMALL_GEAR));
    }

    // NEW ELEMENTS todo
    public static Material MetastableOganesson;
    public static Material MetastableFlerovium;
    public static Material MetastableHassium;

    public static Material Protactinium;
    public static Material UraniumRadioactive;
    public static Material Neptunium;
    public static Material PlutoniumRadioactive;
    public static Material Curium;
    public static Material Berkelium;
    public static Material Californium;
    public static Material Einsteinium;
    public static Material Fermium;
    public static Material Mendelevium;

    // NUCLEAR MATERIALS
    // Thorium
    public static Material ThoriumRadioactive;
    public static Material Thorium232Isotope;
    public static Material Thorium233;

    // Protactinium
    public static Material Protactinium233;

    // Uranium
    public static Material Uranium238Isotope;
    public static Material Uranium233;
    public static Material Uranium234;
    public static Material Uranium235Isotope;
    public static Material Uranium239;

    // Neptunium
    public static Material Neptunium235;
    public static Material Neptunium237;
    public static Material Neptunium239;

    // Plutonium
    //public static Material Plutonium239; todo remove, is in CEu
    public static Material Plutonium240;
    public static Material Plutonium241Isotope;
    public static Material Plutonium244Isotope;
    public static Material Plutonium245;

    // Americium
    public static Material AmericiumRadioactive;
    public static Material Americium241;
    public static Material Americium243;
    public static Material Americium245;

    // Curium
    public static Material Curium245;
    public static Material Curium246;
    public static Material Curium247;
    public static Material Curium250;
    public static Material Curium251;

    // Berkelium
    public static Material Berkelium247;
    public static Material Berkelium249;
    public static Material Berkelium251;

    // Californium
    public static Material Californium251;
    public static Material Californium252;
    public static Material Californium253;
    public static Material Californium256;
    public static Material Californium257;

    // Einsteinium
    public static Material Einsteinium253;
    public static Material Einsteinium255;
    public static Material Einsteinium257;

    // Fermium
    public static Material Fermium257;
    public static Material Fermium258;
    public static Material Fermium259;
    public static Material Fermium262;
    public static Material Fermium263;

    // Mendelevium
    public static Material Mendelevium259;
    public static Material Mendelevium261;
    public static Material Mendelevium263;

    public static SimpleFluidMaterial Carbon12 = new SimpleFluidMaterial("carbon_12", Carbon.materialRGB, "C_12");
    public static SimpleFluidMaterial Carbon13 = new SimpleFluidMaterial("carbon_13", Carbon.materialRGB, "C_13");
    public static SimpleFluidMaterial Nitrogen14 = new SimpleFluidMaterial("nitrogen_14", Nitrogen.materialRGB, "N_14");
    public static SimpleFluidMaterial Nitrogen15 = new SimpleFluidMaterial("nitrogen_15", Nitrogen.materialRGB, "N_15");
    public static SimpleFluidMaterial Calcium44 = new SimpleFluidMaterial("calcium_44", Calcium.materialRGB, "Ca_44");
    public static SimpleFluidMaterial Ytterbium178 = new SimpleFluidMaterial("ytterbium_178", Ytterbium.materialRGB, "Yb_178");
    public static SimpleFluidMaterial Chromium48 = new SimpleFluidMaterial("chromium48", Chrome.materialRGB, true, "Cr_48");
    public static SimpleFluidMaterial Iron52 = new SimpleFluidMaterial("iron52", Iron.materialRGB, true, "Fe_52");
    public static SimpleFluidMaterial Nickel56 = new SimpleFluidMaterial("nickel56", Nickel.materialRGB, true, "Ni_56");
    public static SimpleFluidMaterial Titanium44 = new SimpleFluidMaterial("titanium44", Titanium.materialRGB, true, "Ti_44");
    //public static SimpleFluidMaterial PlasmaChromium48 = new SimpleFluidMaterial("chromium48_plasma", Chrome.materialRGB);
    //public static SimpleFluidMaterial PlasmaIron52 = new SimpleFluidMaterial("iron52_plasma", Iron.materialRGB);
    //public static SimpleFluidMaterial PlasmaNickel56 = new SimpleFluidMaterial("nickel56_plasma", Nickel.materialRGB);
    //public static SimpleFluidMaterial PlasmaTitanium44 = new SimpleFluidMaterial("titanium44_plasma", Titanium.materialRGB);

    public static FluidMaterial LiquidOxygen = new FluidMaterial(919, "liquid_oxygen", 0x81FFFD, MaterialIconSet.FLUID, of(new MaterialStack(Oxygen, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION).setFluidTemperature(54);
    public static FluidMaterial LiquidHydrogen = new FluidMaterial(917, "liquid_hydrogen", 0x3AFFC6, MaterialIconSet.FLUID, of(new MaterialStack(Hydrogen, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION).setFluidTemperature(14);


    //todo move to ceu
    public static FluidMaterial FishOil = new FluidMaterial(999, "fish_oil", 14467421, MaterialIconSet.FLUID, ImmutableList.of(new MaterialStack(RareEarth, 1)), GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION);
    public static IngotMaterial MVSuperconductorBase = new IngotMaterial(976, "mv_superconductor_base", 0x535353, MaterialIconSet.SHINY, 1, ImmutableList.of(new MaterialStack(Cadmium, 5), new MaterialStack(Magnesium, 1), new MaterialStack(Oxygen, 6)), GA_STD_METAL, null, 1200);
    public static IngotMaterial HVSuperconductorBase = new IngotMaterial(975, "hv_superconductor_base", 0x4a2400, MaterialIconSet.SHINY, 1, ImmutableList.of(new MaterialStack(Titanium, 1), new MaterialStack(Barium, 9), new MaterialStack(Copper, 10), new MaterialStack(Oxygen, 20)), GA_STD_METAL, null, 3300);
    public static IngotMaterial EVSuperconductorBase = new IngotMaterial(974, "ev_superconductor_base", 0x005800, MaterialIconSet.SHINY, 1, ImmutableList.of(new MaterialStack(Uranium, 1), new MaterialStack(Platinum, 3)), GA_STD_METAL, null, 4400);
    public static IngotMaterial IVSuperconductorBase = new IngotMaterial(973, "iv_superconductor_base", 0x300030, MaterialIconSet.SHINY, 1, ImmutableList.of(new MaterialStack(Vanadium, 1), new MaterialStack(Indium, 3)), GA_STD_METAL, null, 5200);
    public static IngotMaterial LuVSuperconductorBase = new IngotMaterial(972, "luv_superconductor_base", 0x7a3c00, MaterialIconSet.SHINY, 1, ImmutableList.of(new MaterialStack(Indium, 4), new MaterialStack(Bronze, 8), new MaterialStack(Barium, 2), new MaterialStack(Titanium, 1), new MaterialStack(Oxygen, 14)), GA_STD_METAL, null, 6000);
    public static IngotMaterial ZPMSuperconductorBase = new IngotMaterial(971, "zpm_superconductor_base", 0x111111, MaterialIconSet.SHINY, 1, ImmutableList.of(new MaterialStack(Naquadah, 4), new MaterialStack(Indium, 2), new MaterialStack(Palladium, 6), new MaterialStack(Osmium, 1)), GA_STD_METAL | DISABLE_DECOMPOSITION, null, 8100);
    public static IngotMaterial MVSuperconductor = new IngotMaterial(970, "mv_superconductor", 0x535353, MaterialIconSet.SHINY, 1, of(new MaterialStack(MVSuperconductorBase, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial HVSuperconductor = new IngotMaterial(969, "hv_superconductor", 0x4a2400, MaterialIconSet.SHINY, 1, of(new MaterialStack(HVSuperconductorBase, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial EVSuperconductor = new IngotMaterial(968, "ev_superconductor", 0x005800, MaterialIconSet.SHINY, 1, of(new MaterialStack(EVSuperconductorBase, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial IVSuperconductor = new IngotMaterial(967, "iv_superconductor", 0x300030, MaterialIconSet.SHINY, 1, of(new MaterialStack(IVSuperconductorBase, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial LuVSuperconductor = new IngotMaterial(966, "luv_superconductor", 0x7a3c00, MaterialIconSet.SHINY, 1, of(new MaterialStack(LuVSuperconductorBase, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial ZPMSuperconductor = new IngotMaterial(964, "zpm_superconductor", 0x111111, MaterialIconSet.SHINY, 1, of(new MaterialStack(ZPMSuperconductorBase, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial UVSuperconductorBase = new IngotMaterial(745, "uv_superconductor_base", 0xe0d207, MaterialIconSet.SHINY, 1, ImmutableList.of(new MaterialStack(Naquadria, 4), new MaterialStack(Osmiridium, 3), new MaterialStack(Rutherfordium, 1), new MaterialStack(Samarium, 1)), GA_STD_METAL, null, 8900);
    public static IngotMaterial UVSuperconductor = new IngotMaterial(744, "uv_superconductor", 0xe0d207, MaterialIconSet.SHINY, 1, of(new MaterialStack(UVSuperconductorBase, 1), new MaterialStack(Nitrogen, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);

    // Probably don't move these
    public static IngotMaterial UHVSuperconductorBase = new IngotMaterial(740, "uhv_superconductor_base", 0x359ffc, MaterialIconSet.SHINY, 1, of(new SimpleDustMaterialStack(TBCCODust, 4), new SimpleDustMaterialStack(StrontiumSuperconductorDust, 4), new MaterialStack(Taranium, 1)), GA_STD_METAL | DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE, null, 10000);
    public static IngotMaterial UHVSuperconductor = new IngotMaterial(739, "uhv_superconductor", 0x359ffc, MaterialIconSet.SHINY, 1, of(new MaterialStack(UHVSuperconductorBase, 1), new MaterialStack(Nitrogen, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial UEVSuperconductorBase = new IngotMaterial(738, "uev_superconductor_base", 0x954fe0, MaterialIconSet.SHINY, 1, of(new SimpleDustMaterialStack(ActiniumSuperhydride, 1), new SimpleDustMaterialStack(BETSPerrhenate, 1), new MaterialStack(Vibranium, 2), new MaterialStack(Quantum, 1), new MaterialStack(TriniumTitanium, 1)), GA_STD_METAL | DISABLE_AUTOGENERATED_MIXER_RECIPE | DISABLE_DECOMPOSITION, null, 11150);
    public static IngotMaterial UEVSuperconductor = new IngotMaterial(737, "uev_superconductor", 0x954fe0, MaterialIconSet.SHINY, 1, of(new MaterialStack(UEVSuperconductorBase, 1), new MaterialStack(Nitrogen, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial UIVSuperconductorBase = new IngotMaterial(727, "uiv_superconductor_base", 0x8bf743, MaterialIconSet.SHINY, 1, of(new SimpleDustMaterialStack(BorocarbideDust, 2), new SimpleDustMaterialStack(FullereneSuperconductiveDust, 1), new MaterialStack(MetastableOganesson, 2), new MaterialStack(ProtoAdamantium, 2)), GA_STD_METAL | DISABLE_AUTOGENERATED_MIXER_RECIPE | DISABLE_DECOMPOSITION, null, 11600);
    public static IngotMaterial UIVSuperconductor = new IngotMaterial(726, "uiv_superconductor", 0x8bf743, MaterialIconSet.SHINY, 1, of(new MaterialStack(UIVSuperconductorBase, 1), new MaterialStack(Nitrogen, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial UMVSuperconductorBase = new IngotMaterial(725, "umv_superconductor_base", 0x883afc, MaterialIconSet.SHINY, 1, of(new MaterialStack(BlackTitanium,3), new MaterialStack(SuperheavyHAlloy, 2), new SimpleDustMaterialStack(ChargedCesiumCeriumCobaltIndium, 3), new SimpleDustMaterialStack(RheniumHassiumThalliumIsophtaloylbisdiethylthioureaHexafluorophosphate, 6)), GA_STD_METAL | DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE, null, 12000);
    public static IngotMaterial UMVSuperconductor = new IngotMaterial(724, "umv_superconductor", 0x883afc, MaterialIconSet.SHINY, 1, of(new MaterialStack(UMVSuperconductorBase, 1), new MaterialStack(Nitrogen, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);
    public static IngotMaterial UXVSuperconductorBase = new IngotMaterial(723, "uxv_superconductor_base", 0xe34b5a, MaterialIconSet.SHINY, 1, of(new MaterialStack(Neutronium, 4), new SimpleDustMaterialStack(Legendarium, 5), new SimpleDustMaterialStack(ActiniumSuperhydride,5), new SimpleDustMaterialStack(LanthanumFullereneNanotubes, 4), new SimpleDustMaterialStack(RheniumHassiumThalliumIsophtaloylbisdiethylthioureaHexafluorophosphate, 12)), GA_STD_METAL | DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE, null, 14000);
    public static IngotMaterial UXVSuperconductor = new IngotMaterial(722, "uxv_superconductor", 0xe34b5a, MaterialIconSet.SHINY, 1, of(new MaterialStack(UXVSuperconductorBase, 1), new MaterialStack(Nitrogen, 1)), DISABLE_DECOMPOSITION | DISABLE_AUTOGENERATED_MIXER_RECIPE);

    // MAX superconductor material? (in CEu)

    // todo
    public static FluidMaterial CoalTar = new FluidMaterial(937, "coal_tar", 0x5E3122, MaterialIconSet.FLUID, of(new MaterialStack(Coal, 1), new MaterialStack(RareEarth, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION);
    public static FluidMaterial CoalTarOil = new FluidMaterial(936, "coal_tar_oil", 0xB5B553, MaterialIconSet.FLUID, of(new MaterialStack(CoalTar, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION);
    public static FluidMaterial SulfuricCoalTarOil = new FluidMaterial(935, "sulfuric_coal_tar_oil", 0xFFFFAD, MaterialIconSet.FLUID, of(new MaterialStack(CoalTarOil, 1), new MaterialStack(SulfuricAcid, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION);
    public static FluidMaterial AquaRegia = new FluidMaterial(899, "aqua_regia", 0xFFB132, MaterialIconSet.FLUID, of(new MaterialStack(NitricAcid, 1), new MaterialStack(HydrochloricAcid, 1)), DISABLE_DECOMPOSITION);


    // First Degree Materials
    public static Material Hydrazine;
    public static Material HydrogenPeroxide;
    public static Material PlatinumConcentrate;
    public static Material AmmoniumChloride;
    public static Material RhodiumSulfate;
    public static Material OsmiumTetroxideSolution;
    public static Material IridiumDioxide;
    public static Material SodiumTungstate;
    public static Material AluminoSilicateWool;
    public static Material Dibismusthydroborate;
    public static Material BismuthTellurite;
    public static Material YttriumOxide;
    public static Material PlatinumSalt;
    public static Material PlatinumSaltRefined;
    public static Material PlatinumMetallicPowder;
    public static Material PlatinumResidue;
    public static Material ReprecipitatedPlatinum;
    public static Material PalladiumMetallicPowder;
    public static Material PalladiumSalt;
    public static Material SodiumSulfate;
    public static Material PotassiumDisulfate;
    public static Material LeachResidue;
    public static Material CalciumChloride;
    public static Material SodiumRuthenate;
    public static Material RutheniumTetroxide;
    public static Material IridiumChloride;
    public static Material MetallicSludgeResidue;
    public static Material CrudeRhodiumMetal;
    public static Material SodiumNitrate;
    public static Material ZincSulfate;
    public static Material RhodiumFilterCake;
    public static Material SilverOxide;
    public static Material SilverChloride;
    public static Material PotassiumMetabisulfite;
    public static Material LeadNitrate;
    public static Material SodiumPotassiumAlloy;
    public static Material SodiumFluoride;
    public static Material PotassiumFluoride;
    public static Material FLiNaK;
    public static Material FLiBe;
    public static Material CalciumTungstate;
    public static Material TungsticAcid;
    public static Material TungstenTrioxide;
    public static Material TungstenHexachloride;
    public static Material Rhodochrosite;
    public static Material Fluorite;
    public static Material Columbite;
    public static Material Pyrochlore;
    public static Material IndiumPhospide;
    public static Material Barytocalcite;
    public static Material Witherite;
    public static Material Arsenopyrite;
    public static Material Gallite;
    public static Material Bowieite;
    public static Material Celestine;
    public static Material CubicZirconia;
    public static Material Prasiolite;
    public static Material Zircon;
    public static Material LeadZirconateTitanate;
    public static Material Grisium;
    public static Material Staballoy;
    public static Material HastelloyN;
    public static Material Stellite;
    public static Material Talonite;
    public static Material Nitinol60;
    public static Material BabbittAlloy;
    public static Material HG1223;
    public static Material IncoloyMA956;
    public static Material ZirconiumCarbide;
    public static Material RhodiumPlatedPalladium;
    public static Material Ruridit;
    public static Material GoldAlloy;
    public static Material PreciousMetal;
    public static Material LithiumFluoride;
    public static Material BerylliumFluoride;
    public static Material LeadBismuthEutectic;
    public static Material ReactorSteel;
    public static Material EnrichedNaquadahAlloy;
    public static Material BlackTitanium;
    public static Material ProtoAdamantium;
    public static Material TriniumTitanium;
    public static Material LithiumTitanate;
    public static Material ElectricallyImpureCopper;
    public static Material ThoriaDopedTungsten;
    public static Material BariumTitanate;
    public static Material TantalumHafniumSeaborgiumCarbide;
    public static Material BismuthRuthenate;
    public static Material BismuthIridiate;
    public static Material RutheniumDioxide;
    public static Material GermaniumTungstenNitride;
    public static Material LithiumNiobate;
    public static Material SuperheavyHAlloy;
    public static Material SuperheavyLAlloy;
    public static Material Periodicium;
    public static Material NaquadriaticTaranium;
    public static Material AntimonyPentafluoride;
    public static Material FluoroantimonicAcid;
    public static Material FluoronaquadricAcid;
    public static Material EnrichedFluoronaquadricAcid;
    public static Material FluoronaquadriaticAcid;
    public static Material NaquadahDifluoride;
    public static Material EnrichedNaquadahDifluoride;
    public static Material NaquadriaHexafluoride;
    public static Material RadonDifluoride;
    public static Material RadonNaquadriaoctafluoride;
    public static Material XenonTrioxide;
    public static Material CaesiumFluoride;
    public static Material RadonTrioxide;
    public static Material NaquadriaCaesiumXenonNonfluoride;
    public static Material EnrichedNaquadahhexafluoride;
    public static Material EnrichedXenonHexafluoronaquadate;
    public static Material AuricChloride;
    public static Material BromineTrifluoride;
    public static Material XenoauricFluoroantimonicAcid;
    public static Material NaquadahSulfate;
    public static Material ClearNaquadahLiquid;
    public static Material ComplicatedNaquadahGas;
    public static Material ComplicatedHeavyNaquadah;
    public static Material ComplicatedMediumNaquadah;
    public static Material ComplicatedLightNaquadah;
    public static Material NaquadahGas;
    public static Material LightNaquadah;
    public static Material MediumNaquadah;
    public static Material HeavyNaquadah;
    public static Material FCrackedLightNaquadah;
    public static Material FCrackedMediumNaquadah;
    public static Material FCrackedHeavyNaquadah;
    public static Material LightNaquadahFuel;
    public static Material MediumNaquadahFuel;
    public static Material HeavyNaquadahFuel;
    public static Material ENaquadahSolution;
    public static Material ClearENaquadahLiquid;
    public static Material ComplicatedHeavyENaquadah;
    public static Material ComplicatedMediumENaquadah;
    public static Material ComplicatedLightENaquadah;
    public static Material LightENaquadah;
    public static Material MediumENaquadah;
    public static Material HeavyENaquadah;
    public static Material RnCrackedLightNaquadah;
    public static Material RnCrackedMediumENaquadah;
    public static Material RnCrackedHeavyENaquadah;
    public static Material LightENaquadahFuel;
    public static Material MediumENaquadahFuel;
    public static Material HeavyENaquadahFuel;
    public static Material NaquadriaSolution;
    public static Material HyperFuelI;
    public static Material HyperFuelII;
    public static Material HyperFuelIII;
    public static Material HyperFuelIV;
    public static Material ChlorosulfonicAcid;
    public static Material SiliconFluoride;
    public static Material PhosphorusTrichloride;
    public static Material PhosphorylChloride;
    public static Material RheniumSulfuricSolution;
    public static Material AmmoniumSulfate;
    public static Material AmmoniumPerrhenate;
    public static Material ElectronDegenerateRheniumPlasma;
    public static Material LiquidHelium;
    public static Material BoricAcid;
    public static Material FluoroBoricAcid;
    public static Material BoronFluoride;
    public static Material HydrobromicAcid;
    public static Material ThionylChloride;
    public static Material Silvertetrafluoroborate;
    public static Material PotassiumHydroxide;
    public static Material ZrHfChloride;
    public static Material ZrHfOxyChloride;
    public static Material ZincPoorMix;
    public static Material IronPoorMix;
    public static Material IndiumHydroxideConcentrate;
    public static Material ZincAmalgam;
    public static Material GermaniumChloride;
    public static Material Ozone;
    public static Material NitrogenPentoxide;
    public static Material CarbonSulfide;
    public static Material ChloroPlatinicAcid;
    public static Material SuperheavyMix;
    public static Material HotMetastableOganesson;
    public static Material TitaniumTetrafluoride;
    public static Material Titanium50Tetrafluoride;
    public static Material CNOcatalyst;
    public static Material OgannesonBreedingBase;
    public static Material FlYbPlasma;
    public static Material HeliumCNO;
    public static Material SelenateSolution;
    public static Material TitaniumDisulfate;
    public static Material FluoroniobicAcid;
    public static Material FluorotantalicAcid;
    public static Material OxypentafluoroNiobate;
    public static Material HeptafluoroTantalate;
    public static Material HydroselenicAcid;
    public static Material BariumTitanatePreparation;
    public static Material CarbonTetrachloride;
    public static Material ActiniumSuperhydride;
    public static Material Diborane;
    public static Material FluorosilicicAcid;
    public static Material AmmoniumFluoride;
    public static Material MercuryNitrate;
    public static Material KryptonDifluoride;
    public static Material DeuteriumSuperheavyMix;
    public static Material ScandiumTitanium50Mix;
    public static Material RadonRadiumMix;
    public static Material Trichloroflerane;
    public static Material NobleGasesMixture;
    public static Material NonMetals;
    public static Material Iron2Chloride;
    public static Material FluorophosphoricAcid;
    public static Material ChloroauricAcid;
    public static Material LiquidHelium;
    public static Material SuperfluidHelium;
    public static Material LiquidHelium3;
    public static Material Helium4;
    public static Material HotNitrogen;
    public static Material SupercriticalDeuterium;
    public static Material SupercriticalSodium;
    public static Material NaquadricCompound;
    public static Material EnrichedNaquadricCompound;
    public static Material NaquadriaticCompound;
    public static Material QuantumDots;
    public static Material SemisolidHydrogen;
    public static Material MicrocrystallizingHydrogen;
    public static Material NitrousAcid;
    public static Material SelenousAcid;
    public static Material TetrafluoroboricAcid;
    public static Material AntimonyTrifluoride;
    public static Material IndiumTrifluoride;
    public static Material IndiumTrioxide;
    public static Material NaquadahConcentrate;
    public static Material EnrichedNaquadahConcentrate;
    public static Material NaquadriaConcentrate;
    public static Material AuricFluoride;
    public static Material ThUSludge;
    public static Material LanthanumOxide;
    public static Material PraseodymiumOxide;
    public static Material NeodymiumOxide;
    public static Material CeriumOxide;
    public static Material EuropiumOxide;
    public static Material GadoliniumOxide;
    public static Material SamariumOxide;
    public static Material TerbiumOxide;
    public static Material DysprosiumOxide;
    public static Material HolmiumOxide;
    public static Material ErbiumOxide;
    public static Material ThuliumOxide;
    public static Material YtterbiumOxide;
    public static Material LutetiumOxide;
    public static Material ScandiumOxide;
    public static Material CalciumCarbide;
    public static Material CalciumHydroxide;
    public static Material SilicaGel;
    public static Material ZirconiumTetrachloride;
    public static Material SiliconCarbide;
    public static Material GoldDepleteMolybdenite;
    public static Material MolybdenumConcentrate;
    public static Material MolybdenumTrioxide;
    public static Material CopperChloride;
    public static Material BismuthChloride;
    public static Material LeadChloride;
    public static Material ZirconiumTetrafluoride;
    public static Material BariumDifluoride;
    public static Material LanthanumTrifluoride;
    public static Material AluminiumTrifluoride;
    public static Material ErbiumTrifluoride;
    public static Material PdIrReOCeOS;
    public static Material MgClBromide;
    public static Material SodiumNitrite;
    public static Material ZnFeAlClCatalyst;
    public static Material AluminiumChloride;
    public static Material AuPdCCatalyst;
    public static Material TinChloride;
    public static Material VanadiumSlagDust;
    public static Material SodiumVanadate;
    public static Material AmmoniumVanadate;
    public static Material VanadiumOxide;
    public static Material BariumSulfide;
    public static Material BariumCarbonate;
    public static Material BariumOxide;
    public static Material BariumAluminate;
    public static Material CaesiumHydroxide;
    public static Material AluminiumHydroxide;
    public static Material PotassiumCarbonate;
    public static Material NiAlOCatalyst;
    public static Material FeCrOCatalyst;
    public static Material LithiumChloride;
    public static Material NickelChloride;
    public static Material PotassiumSulfate;
    public static Material AluminiumSulfate;
    public static Material BariumHydroxide;
    public static Material HafniumOxide;
    public static Material SiliconChloride;
    public static Material HafniumChloride;
    public static Material ZincLeachingResidue;
    public static Material IndiumHydroxide;
    public static Material ThalliumResidue;
    public static Material ThalliumChloride;
    public static Material ZincChloride;
    public static Material SodiumSulfite;
    public static Material GermaniumOxide;
    public static Material DisodiumPhosphate;
    public static Material SodiumAzanide;
    public static Material SodiumAzide;
    public static Material AluminiumHydride;
    public static Material SodiumHydride;
    public static Material MagnesiumSulfate;
    public static Material SodiumMolybdate;
    public static Material StrontiumSulfate;
    public static Material StrontiumOxide;
    public static Material PalladiumChloride;
    public static Material PotassiumTetrachloroplatinate;
    public static Material NiAlCatalyst;
    public static Material TitaniumNitrate;
    public static Material AnodicSlime;
    public static Material TelluriumOxide;
    public static Material SeleniumOxide;
    public static Material ManganeseSulfate;
    public static Material NbTaContainingDust;
    public static Material IronSulfate;
    public static Material StrontiumCarbonate;
    public static Material SodiumBicarbonate;
    public static Material SodiumHypochlorite;
    public static Material CopperGalliumIndiumMix;
    public static Material LanthanumCalciumManganate;
    public static Material IronPlatinumCatalyst;
    public static Material YttriumNitrate;
    public static Material CopperNitrate;
    public static Material BariumNitrate;
    public static Material WellMixedYBCOxides;
    public static Material PiledTBCC;
    public static Material ActiniumHydride;
    public static Material IronIodide;
    public static Material PotassiumIodide;
    public static Material ThalliumIodide;
    public static Material ScandiumIodide;
    public static Material RubidiumIodide;
    public static Material IndiumIodide;
    public static Material GalliumIodide;
    public static Material CarbonylPurifiedIron;
    public static Material SodiumThiosulfate;
    public static Material SodiumBromide;
    public static Material FranciumCarbide;
    public static Material BoronCarbide;
    public static Material MixedAstatideSalts;
    public static Material SodiumIodide;
    public static Material SodiumIodate;
    public static Material SodiumPeriodate;
    public static Material SodiumSeaborgate;
    public static Material OsmiumTetroxide;
    public static Material StrontiumChloride;
    public static Material YttriumEuropiumVanadate;
    public static Material StrontiumEuropiumAluminate;
    public static Material BariumStrontiumTitanate;
    public static Material PotassiumManganate;
    public static Material BariumChloride;
    public static Material TantalumOxide;
    public static Material ZirconylChloride;
    public static Material LeadSelenide;
    public static Material BoronOxide;
    public static Material LithiumAluminiumFluoride;
    public static Material HafniumCarbide;
    public static Material TantalumCarbide;
    public static Material SeaborgiumCarbide;
    public static Material AluminiumNitrate;
    public static Material CaesiumBromide;
    public static Material FluoroapatiteSolidResidue; //todo unused
    public static Material ApatiteSolidResidue;
    public static Material AmmoniumBifluoride;
    public static Material SodiumArsenate;
    public static Material PureSodiumVanadate;
    public static Material AmmoniumCarbonate;
    public static Material CadmiumSulfide;
    public static Material BismuthVanadate;
    public static Material CopperArsenite;
    public static Material MercuryIodide;
    public static Material CobaltZincOxide;
    public static Material ScheelesGreen;
    public static Material CobaltAluminate;
    public static Material HanPurple;
    public static Material ChromeYellow;
    public static Material ChromeOrange;
    public static Material ManganeseIIIOxide;
    public static Material MercuryChloride;
    public static Material LithiumHydride;
    public static Material NiobiumChloride;
    public static Material NiobiumHydroxide;
    public static Material MagnesiumFluoride;
    public static Material ZincSulfide;
    public static Material LithiumNiobateNanoparticles;
    public static Material LithiumHydroxide;
    public static Material RhReNqCatalyst;
    public static Material FranciumCaesiumCadmiumBromide;
    public static Material ZincSelenide;
    public static Material PotassiumBromide;
    public static Material PotassiumBromate;
    public static Material SodiumPertechnetate;
    public static Material PotassiumPertechnate;
    public static Material PotassiumPerrhenate;
    public static Material LithiumIodide;
    public static Material ManganeseFluoride;
    public static Material GermaniumSulfide;
    public static Material BismuthGermanate;
    public static Material CaesiumIodide;
    public static Material CadmiumTungstate;
    public static Material SodiumOxide;
    public static Material SodiumPerchlorate;
    public static Material Lanthanoids;
    public static Material Actinoids;
    public static Material Alkalis;
    public static Material PreciousMetals;
    public static Material LightTranstionMetals;
    public static Material RefractoryMetals;
    public static Material PostTransitionMetals;
    public static Material RheniumChloride;
    public static Material AntimonyTrichloride;
    public static Material LithiumCobaltOxide;
    public static Material LithiumTriflate;
    public static Material SiliconNanoparticles;
    public static Material Halloysite;
    public static Material GalliumChloride;
    public static Material LanthanumNickelOxide;
    public static Material BorocarbideDust;
    public static Material HassiumChloride;
    public static Material SodiumMetavanadate;
    public static Material PotassiumPeroxymonosulfate;
    public static Material SilverPerchlorate;
    public static Material SodiumChlorate;
    public static Material CopperLeach;
    public static Material CaliforniumTrioxide;
    public static Material CaliforniumTrichloride;
    public static Material IridiumTrioxide;
    public static Material PotassiumHydroxylaminedisulfonate;
    public static Material NitroniumTetrafluoroborate;
    public static Material NitrosoniumTetrafluoroborate;
    public static Material PdCCatalyst;
    public static Material PotassiumBisulfite;
    public static Material PotassiumNitrite;
    public static Material HydroxylammoniumSulfate;
    public static Material Legendarium;
    public static IngotMaterial Polyimide = new IngotMaterial(992, "polyimide", 0xFF7F50, MaterialIconSet.DULL, 1, of(new MaterialStack(Carbon, 22), new MaterialStack(Hydrogen, 12), new MaterialStack(Nitrogen, 2), new MaterialStack(Oxygen, 6)), GENERATE_PLATE | FLAMMABLE | NO_SMASHING | SMELT_INTO_FLUID | DISABLE_DECOMPOSITION);
    public static IngotMaterial FluorinatedEthylenePropylene = new IngotMaterial(988, "fluorinated_ethylene_propylene", 0xC8C8C8, MaterialIconSet.DULL, 1, of(new MaterialStack(Carbon, 5), new MaterialStack(Fluorine, 10)), GENERATE_PLATE | FLAMMABLE | NO_SMASHING | SMELT_INTO_FLUID | DISABLE_DECOMPOSITION);


    // Second Degree Materials
    public static Material PalladiumAmmonia;
    public static Material RhodiumSulfateSolution;
    public static Material RutheniumTetroxideSolution;
    public static Material RhodiumSaltSolution;
    public static Material RhodiumFilterCakeSolution;
    public static Material EglinSteelBase;
    public static Material MicaPulp;
    public static Material CircuitCompoundMK3;
    public static Material Zirkelite;
    public static Material PalladiumRawPowder;
    public static Material RarestMetalResidue;
    public static Material IrMetalResidue;
    public static Material PGSDResidue;
    public static Material RhodiumNitrate;
    public static Material OrganicFertilizer;
    public static Material Caliche;
    public static Material FluoroApatite;
    public static Material RhodiumSalt;
    public static Material Inconel625;
    public static Material MaragingSteel250;
    public static Material Tumbaga;
    public static Material Enderium;
    public static Material AbyssalAlloy;
    public static Material Incoloy813;
    public static Material TungstenTitaniumCarbide;
    public static Material Inconel792;
    public static Material Lafium;
    public static Material Zeron100;
    public static Material WoodsGlass;
    public static Material NaquadricSolution;
    public static Material EnrichedNaquadricSolution;
    public static Material NaquadriaticSolution;
    public static Material CesiumXenontrioxideFluoride;
    public static Material NitrylFluoride;
    public static Material NitrosoniumOctafluoroxenate;
    public static Material NaquadriaCesiumfluoride;
    public static Material NaquadahSolution;
    public static Material AmmoniumNitrate;
    public static Material SodiumNitrateSolution;
    public static Material IodizedBrine;
    public static Material IodineSlurry;
    public static Material Hydroxylamine;
    public static Material HydroxylamineDisulfate;
    public static Material SodiumHydroxideBauxite;
    public static Material AcidicSaltWater;
    public static Material SulfuricBromineSolution;
    public static Material HotVapourMixture;
    public static Material DampBromine;
    public static Material RareEarthHydroxidesSolution;
    public static Material RareEarthChloridesSolution;
    public static Material LaNdOxidesSolution;
    public static Material SmGdOxidesSolution;
    public static Material TbHoOxidesSolution;
    public static Material ErLuOxidesSolution;
    public static Material CleanAmmoniaSolution;
    public static Material SilicaGelBase;
    public static Material PiranhaSolution;
    public static Material WaterAgarMix;
    public static Material RedOil;
    public static Material ChlorideLeachedSolution;
    public static Material MolybdenumFlue;
    public static Material VanadiumWasteSolution;
    public static Material UranylChlorideSolution;
    public static Material UranylNitrateSolution;
    public static Material UraniumSulfateWasteSolution;
    public static Material PurifiedUranylNitrate;
    public static Material UraniumDiuranate;
    public static Material UraniumRefinementWasteSolution;
    public static Material ThoriumNitrateSolution;
    public static Material SodiumHexafluoroaluminate;
    public static Material SodiumCarbonateSolution;
    public static Material SodiumSulfateSolution;
    public static Material SodiumChromateSolution;
    public static Material SodiumDichromateSolution;
    public static Material DissolvedLithiumOre;
    public static Material LithiumCarbonateSolution;
    public static Material LithiumChlorideSolution;
    public static Material CalicheIodateBrine;
    public static Material IodideSolution;
    public static Material CalicheNitrateSolution;
    public static Material CalicheIodineBrine;
    public static Material ZirconChlorinatingResidue;
    public static Material ZincExhaustMixture;
    public static Material ZincSlagSlurry;
    public static Material AcidicMetalSlurry;
    public static Material SeparatedMetalSlurry;
    public static Material CadmiumThalliumLiquor;
    public static Material CadmiumSulfateSolution;
    public static Material ThalliumSulfateSolution;
    public static Material GermanicAcidSolution;
    public static Material SodiumHydroxideSolution;
    public static Material LithiumHydroxideSolution;
    public static Material LithiumPeroxideSolution;
    public static Material PureUranylNitrateSolution;
    public static Material SodiumLithiumSolution;
    public static Material MagnesiumContainingBrine;
    public static Material BrominatedBrine;
    public static Material AcidicBrominatedBrine;
    public static Material SelenateTellurateMix;
    public static Material CopperRefiningSolution;
    public static Material ImpureAluminiumHydroxideSolution;
    public static Material PureAluminiumHydroxideSolution;
    public static Material RedMud;
    public static Material NeutralisedRedMud;
    public static Material FerricREEChloride;
    public static Material RedSlurry;
    public static Material DiluteNitricAcid;
    public static Material NbTaFluorideMix;
    public static Material REEThUSulfateSolution;
    public static Material RareEarthNitrateSolution;
    public static Material AlkalineEarthSulfateSolution;
    public static Material CalciumCarbonateSolution;
    public static Material BariumSulfateSolution;
    public static Material BentoniteClaySlurry;
    public static Material AstatideSolution;
    public static Material BariumChlorideSolution;
    public static Material IronCarbonyl;
    public static Material PurifiedIronCarbonyl;
    public static Material BismuthNitrateSoluton;
    public static Material PrYHoNitrateSolution;
    public static Material PhosphorousArsenicSolution;
    public static Material AmmoniumBifluorideSolution;
    public static Material LuTmYChlorideSolution;
    public static Material BismuthVanadateSolution;
    public static Material SeaborgiumDopedNanotubes;
    public static Material FullereneDopedNanotubes;
    public static Material LiquidZBLAN;
    public static Material GrapheneOxidationSolution;
    public static Material SupercriticalCO2;
    public static Material LiquidEnrichedHelium;
    public static Material LiquidNitrogen;
    public static Material RheniumScrubbedSolution;
    public static Material NeutroniumDopedNanotubes;
    public static Material SupercriticalSteam;
    public static Material SupercriticalSodiumPotassiumAlloy;
    public static Material SupercriticalFLiNaK;
    public static Material SupercriticalFLiBe;
    public static Material SupercriticalLeadBismuthEutectic;
    public static Material ApatiteAcidicLeach;
    public static Material FluoroapatiteAcidicLeach;
    public static Material SilicaAluminaGel;
    public static Material ZeoliteSievingPellets;
    public static Material WetZeoliteSievingPellets;
    public static Material ZBLANDust;
    public static Material VanadiumSlag;
    public static Material PotassiumUranylTricarbonate;
    public static Material UraniumPeroxideThoriumOxide;
    public static Material UraniumThoriumOxide;
    public static Material UranylThoriumSulfate;
    public static Material UranylThoriumNitrate;
    public static Material UraniumOxideThoriumNitrate;
    public static Material GrapheneOxidationResidue;
    public static Material ZincCokePellets;
    public static Material CadmiumZincDust;
    public static Material UranylNitrate;
    public static Material SodiumSalts;
    public static Material PotassiumMagnesiumSalts;
    public static Material CalciumMagnesiumSalts;
    public static Material SodiumAluminiumHydride;
    public static Material LithiumAluminiumHydride;
    public static Material SodiumPhosphomolybdate;
    public static Material SodiumPhosphotungstate;
    public static Material LeadNitrateCalciumMixture;
    public static Material TinSlag;
    public static Material NiobiumTantalumOxide;
    public static Material FusedColumbite;
    public static Material LeachedColumbite;
    public static Material FusedTantalite;
    public static Material LeachedTantalite;
    public static Material ColumbiteMinorOxideResidue;
    public static Material TantaliteMinorOxideResidue;
    public static Material LeachedPyrochlore;
    public static Material AcidicLeachedPyrochlore;
    public static Material PotasssiumFluoroNiobate;
    public static Material PotasssiumFluoroTantalate;
    public static Material BariumPeroxide;
    public static Material CopperGalliumIndiumSelenide;
    public static Material UVAHalideMix;
    public static Material WhiteHalideMix;
    public static Material BlueHalideMix;
    public static Material GreenHalideMix;
    public static Material RedHalideMix;
    public static Material LeadScandiumTantalate;
    public static Material MagnetorestrictiveAlloy;
    public static Material RawSienna;
    public static Material BurnedSienna;
    public static Material TitaniumYellow;
    public static Material AmmoniumManganesePhosphate;
    public static Material PotassiumNonahydridotechnetate;
    public static Material PotassiumNonahydridorhenate;
    public static Material PalladiumLoadedRutileNanoparticles;
    public static Material PurifiedColumbite;
    public static Material PurifiedPyrochlore;
    public static Material ChargedCesiumCeriumCobaltIndium;
    public static Material SulfurCoatedHalloysite;
    public static Material NickelOxideHydroxide;
    public static Material TBCCODust;
    public static Material StrontiumSuperconductorDust;
    public static Material FullereneSuperconductiveDust;
    public static Material GoldLeach;
    public static Material IridiumTrichlorideSolution;
    public static Material Quantum;
    public static Material BoronFranciumCarbide;
    public static Material TlTmCesiumIodide;
    public static Material RocketFuelH8N4C2O4;
    public static Material Phosgene;



    // Third Degree Materials
    public static Material HotRutheniumTetroxideSolution;
    public static Material AcidicOsmiumSolution;
    public static Material AcidicIridiumSolution;
    public static Material MagnetoResonatic ;
    public static Material EglinSteel;
    public static Material HastelloyX78;
    public static Material TitanSteel;
    public static Material Cinobite;
    public static Material IodineBrineMix;
    public static Material MetalHydroxideMix;
    public static Material CaCBaSMixture;
    public static Material LubricantClaySlurry;
    public static Material ATLEthylene;
    public static Material ErbiumDopedZBLANDust;
    public static Material RoastedSpodumene;
    public static Material RoastedLepidolite;
    public static Material CassiteriteCokePellets;
    public static Material LanthanumFullereneNanotubes;

    // Fourth Degree Materials
    public static Material Pyrotheum;
    public static Material Blizz;
    public static Material HastelloyK243;
    public static Material Pikyonium;
    public static Material CalciumSalts;
    public static Material RheniumHassiumThalliumIsophtaloylbisdiethylthioureaHexafluorophosphate;


    // Fifth Degree Materials
    public static Material Cryotheum;
    public static Material HDCS;

    // Sixth Degree Materials
    public static Material SupercooledCryotheum;


    // Organic Chemistry Materials
    public static Material Anthracene;
    public static Material MonoMethylHydrazine;
    public static Material EthylAnthraQuinone;
    public static Material EthylAnthraHydroQuinone;
    public static Material DenseHydrazineFuelMixture;
    public static Material RocketFuelCN3H7O3;
    public static Material SodiumFormate;
    public static Material FormicAcid;
    public static Material PhthalicAnhydride;
    public static Material Polyetheretherketone;
    public static Material Zylon;
    public static Material FullerenePolymerMatrix;
    public static Material CarbonNanotubes;
    public static Material Polyurethane;
    public static Material PEDOT;
    public static Material Butyraldehyde;
    public static Material Ethylhexanol;
    public static Material DiethylhexylPhosphoricAcid;
    public static Material Turpentine;
    public static Material Acetylene;
    public static Material Formaldehyde;
    public static Material PropargylAlcohol;
    public static Material PropargylChloride;
    public static Material Citral;
    public static Material BetaIonone;
    public static Material VitaminA;
    public static Material EthyleneOxide;
    public static Material Ethanolamine;
    public static Material Biotin;
    public static Material B27Supplement;
    public static Material EGF;
    public static Material Aniline;
    public static Material Sulfanilamide;
    public static Material Ethanol100;
    public static Material LinoleicAcid;
    public static Material CarbonTetrafluoride;
    public static Material TributylPhosphate;
    public static Material Butanol;
    public static Material HydrogenCyanide;
    public static Material SodiumCyanide;
    public static Material GoldCyanide;
    public static Material BenzenediazoniumTetrafluoroborate;
    public static Material FluoroBenzene;
    public static Material Fluorotoluene;
    public static Material OrthoXylene;
    public static Material OrthoXyleneZeoliteMixture;
    public static Material ParaXylene;
    public static Material Dibromomethylbenzene;
    public static Material AceticAnhydride;
    public static Material Isochloropropane;
    public static Material Resorcinol;
    public static Material Dinitrodipropanyloxybenzene;
    public static Material Naphthaldehyde;
    public static Material Diisopropylcarbodiimide;
    public static Material Pyridine;
    public static Material Phenylpentanoicacid;
    public static Material Dimethylsulfide;
    public static Material BenzoylChloride;
    public static Material PCBA;
    public static Material PCBS;
    public static Material Ferrocene;
    public static Material Ferrocenylfulleropyrrolidine;
    public static Material Hydroquinone;
    public static Material SodiumAcetate;
    public static Material Methylamine;
    public static Material IsopropylAlcohol;
    public static Material RichNitrogenMix;
    public static Material OxidisedNitrogenMix;
    public static Material PurifiedNitrogenMix;
    public static Material CarbonatedEthanolamine;
    public static Material AmmoniaRichMix;
    public static Material KeroseneIodineSolution;
    public static Material MesitylOxide;
    public static Material MethylIsobutylKetone;
    public static Material ThiocyanicAcid;
    public static Material Diethylether;
    public static Material TannicAcid;
    public static Material AcryloNitrile;
    public static Material SodiumThiocyanate;
    public static Material PolyacrylonitrileSolution;
    public static Material MethylFormate;
    public static Material WetFormamide;
    public static Material Formamide;
    public static Material AmineMixture;
    public static Material DimethylthiocarbamoilChloride;
    public static Material Trimethylamine;
    public static Material Mercaphenol;
    public static Material Dimethylformamide;
    public static Material HydrogenCrackedDMF;
    public static Material Oct1ene;
    public static Material CetaneTrimethylAmmoniumBromide;
    public static Material AmmoniumPersulfate;
    public static Material ButylLithium;
    public static Material Acetaldehyde;
    public static Material Benzaldehyde;
    public static Material Dibenzylideneacetone;
    public static Material TrimethyltinChloride;
    public static Material Cyclooctadiene;
    public static Material NbTaSeparationMixture;
    public static Material WetEthyleneOxide;
    public static Material EthyleneGlycol;
    public static Material Chloroethanol;
    public static Material Choline;
    public static Material ViscoelasticPolyurethane;
    public static Material ViscoelasticPolyurethaneFoam;
    public static Material TolueneDiisocyanate;
    public static Material Aminophenol;
    public static Material Hydroxyquinoline;
    public static Material Perbromothiophene;
    public static Material Dimethylthiophene;
    public static Material EDOT;
    public static Material CitricAcid;
    public static Material OxalicAcid;
    public static Material Trimethylchlorosilane;
    public static Material Dibromoacrolein;
    public static Material Bromohydrothiine;
    public static Material Lithiumthiinediselenide;
    public static Material Bromobutane;
    public static Material Biperfluoromethanedisulfide;
    public static Material BariumTriflateSolution;
    public static Material BariumStrontiumAcetateSolution;
    public static Material TitaniumIsopropoxide;
    public static Material BariumStrontiumTitanatePreparation;
    public static Material Chloroethane;
    public static Material IsopropylAcetate;
    public static Material ChlorinatedSolvents;
    public static Material Dichloromethane;
    public static Material ButanolGas;
    public static Material Tributylamine;
    public static Material CrudeAluminaSolution;
    public static Material AluminaSolution;
    public static Material AmmoniumCyanate;
    public static Material Ethylenediamine;
    public static Material EDTASolution;
    public static Material EDTA;
    public static Material Glycine;
    public static Material Nitrotoluene;
    public static Material Naphthylamine;
    public static Material Acetoacetanilide;
    public static Material Quinizarin;
    public static Material Toluenesulfonate;
    public static Material Isopropylsuccinate;
    public static Material MaleicAnhydride;
    public static Material Benzonitrile;
    public static Material AmmoniumNiobiumOxalateSolution;
    public static Material DielectricMirrorFormationMix;
    public static Material Iodobenzene;
    public static Material Amino3phenol;
    public static Material Dimethylnaphthalene;
    public static Material IodineMonochloride;
    public static Material AcetylatingReagent;
    public static Material Dihydroiodotetracene;
    public static Material Dichlorodicyanobenzoquinone;
    public static Material Dichlorodicyanohydroquinone;
    public static Material IodobenzoicAcid;
    public static Material Methoxybenzaldehyde;
    public static Material Butylaniline;
    public static Material MBBA;
    public static Material PotassiumEthoxide;
    public static Material TetraethylammoniumBromide;
    public static Material Hexanediol;
    public static Material Hexamethylenediamine;
    public static Material Tertbutanol;
    public static Material Triaminoethaneamine;
    public static Material TertButylAzidoformate;
    public static Material AminatedFullerene;
    public static Material Azafullerene;
    public static Material Ethylamine;
    public static Material Trimethylsilane;
    public static Material Phenylsodium;
    public static Material Difluoroaniline;
    public static Material Succinaldehyde;
    public static Material NDifluorophenylpyrrole;
    public static Material PhotopolymerSolution;
    public static Material GlucoseIronSolution;
    public static Material Methylethanolamine;
    public static Material Methylguanidine;
    public static Material Methylnitronitrosoguanidine;
    public static Material IsoamylAlcohol;
    public static Material Octanol;
    public static Material Trioctylamine;
    public static Material RheniumSeparationMixture;
    public static Material AcetylsulfanilylChloride;
    public static Material BenzoylPeroxide;
    public static Material Propadiene;
    public static Material PhenylenedioxydiaceticAcid;
    public static Material Diethylthiourea;
    public static Material Isophthaloylbisdiethylthiourea;
    public static Material SodiumAlginateSolution;
    public static Material AscorbicAcid;
    public static Material DehydroascorbicAcid;
    public static Material Cyclopentadiene;
    public static Material Oxydianiline;
    public static Material PolyamicAcid;
    public static Material Hexafluoropropylene;
    public static Material Dimethylether;
    public static Material Dimethoxyethane;
    public static Material LithiumCyclopentadienide;
    public static Material CaliforniumCyclopentadienide;
    public static Material StearicAcid;
    public static Material Trioctylphosphine;
    public static Material Toluidine;
    public static Material HydroxylamineHydrochloride;
    public static Material Glyoxal;
    public static Material BenzylChloride;
    public static Material Benzylamine;
    public static Material Tetrahydrofuran;
    public static Material Triethylamine;
    public static Material BetaPinene;
    public static Material Glutamine;
    public static Material PotassiumCyanide;
    public static Material SuccinicAcid;
    public static Material Succinimide;
    public static Material Bromosuccinimide;
    public static Material Benzophenanthrenylacetonitrile;
    public static Material UnfoldedFullerene;
    public static Material Fullerene;
    public static Material TiAlChloride;
    public static Material Dimethylaminopyridine;
    public static Material SodiumEthoxide;
    public static Material Sarcosine;
    public static Material Difluorobenzophenone;
    public static Material PdFullereneMatrix;
    public static Material Terephthalaldehyde;
    public static Material PreZylon;
    public static Material Cyanonaphthalene;
    public static Material Triphenylphosphine;
    public static Material Methylbenzophenanthrene;
    public static Material AcrylicFibers;
    public static Material Glucosamine;
    public static Material PolystyreneNanoParticles;
    public static Material Fructose;
    public static Material Glucose;
    public static Material Biphenyl;
    public static Material Diiodobiphenyl;
    public static Material Bipyridine;
    public static Material PalladiumBisDibenzylidieneacetone;
    public static Material NickelTriphenylPhosphite;
    public static Material Dichlorocycloctadieneplatinium;
    public static Material GrapheneNanotubeMix;
    public static Material GrapheneAlignedCNT;
    public static Material DehydratedLignite;
    public static Material BCEPellet;
    public static Material ActiniumOxalate;
    public static Material LanthanumFullereneMix;
    public static Material LanthanumEmbeddedFullerene;
    public static Material BariumTriflate;
    public static Material ScandiumTriflate;
    public static Material TitaniumCyclopentadienyl;
    public static Material BETS;
    public static Material Urea;
    public static Material PotassiumFerrocyanide;
    public static Material PrussianBlue;
    public static Material DiaminostilbenedisulfonicAcid;
    public static Material Nigrosin;
    public static Material DirectBrown;
    public static Material DianilineterephthalicAcid;
    public static Material Quinacridone;
    public static Material DiarylideYellow;
    public static Material AlizarineCyanineGreen;
    public static Material Aminoanthraquinone;
    public static Material IndanthroneBlue;
    public static Material Diketopyrrolopyrrole;
    public static Material Mauveine;
    public static Material Indigo;
    public static Material Tetrabromoindigo;
    public static Material CyanIndigoDye;
    public static Material Fluorescein;
    public static Material Erythrosine;
    public static Material SodiumSulfanilate;
    public static Material Anthraquinone;
    public static Material PalladiumAcetate;
    public static Material RhodamineB;
    public static Material Stilbene;
    public static Material Tetracene;
    public static Material DitertbutylDicarbonate;
    public static Material IBX;
    public static Material SaccharicAcid;
    public static Material AdipicAcid;
    public static Material TetraethylammoniumNonahydridides;
    public static Material PolycyclicAromaticMix;
    public static Material GrapheneOxide;
    public static Material GraphiteOxide;
    public static Material GrapheneGelSuspension;
    public static Material DryGrapheneGel;
    public static Material MercuryAcetate;
    public static Material CalciumCyanamide;
    public static Material Xylose;
    public static Material FluorideBatteryElectrolyte;
    public static Material Sorbose;
    public static Material CalciumAlginate;
    public static Material BETSPerrhenate;
    public static Material Durene;
    public static Material PyromelliticDianhydride;
    public static Material SuccinicAnhydride;
    public static Material AmmoniumAcetate;
    public static Material Acetamide;
    public static Material Acetonitrile;
    public static Material NHydroxysuccinimide;
    public static Material Hexabenzylhexaazaisowurtzitane;
    public static Material SuccinimidylAcetate;
    public static Material DibenzylTetraacetylhexaazaisowurtzitane;
    public static Material HexanitroHexaaxaisowurtzitane;
    public static Material Hexamethylenetetramine;
    public static Material Tetraacetyldinitrosohexaazaisowurtzitane;
    public static Material CrudeHexanitroHexaaxaisowurtzitane;

    // Unknown Composition Materials
    public static FluidMaterial Kerosene = new FluidMaterial(933, "kerosene", 0xD570D5, MaterialIconSet.FLUID, of(new MaterialStack(RareEarth, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION);
    public static FluidMaterial RP1RocketFuel = new FluidMaterial(921, "rocket_fuel_c", 0xFF503C, MaterialIconSet.FLUID, of(new MaterialStack(RareEarth, 1), new MaterialStack(Oxygen, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION);
    public static FluidMaterial RP1 = new FluidMaterial(920, "rp", 0xFF6E5D, MaterialIconSet.FLUID, of(new MaterialStack(RareEarth, 1)), NO_RECYCLING | GENERATE_FLUID_BLOCK | DISABLE_DECOMPOSITION);
    public static FluidMaterial IodizedOil = new FluidMaterial(711, "iodized_oil", 0x666666, MaterialIconSet.FLUID, of(), 0);
    public static DustMaterial NdYAG = new DustMaterial(688,"nd_yag",0xcf8acf,MaterialIconSet.SHINY,6,of(),SMELT_INTO_FLUID);
    public static DustMaterial PrHoYLF = new DustMaterial(687,"prho_ylf",0x6f20af,MaterialIconSet.SHINY,6,of(),SMELT_INTO_FLUID);
    public static DustMaterial LuTmYVO = new DustMaterial(686,"lutm_yvo",0x206faf,MaterialIconSet.SHINY,6,of(),SMELT_INTO_FLUID);
    public static IngotMaterial HeavyQuarkDegenerateMatter = new IngotMaterial(682,"heavy_quark_degenerate_matter",0x5dbd3a,MaterialIconSet.SHINY,6,of(), GA_CORE_METAL,null, 13000);
    public static IngotMaterial QCDMatter = new IngotMaterial(673, "qcd_confined_matter", 0xeb9e3f, MaterialIconSet.SHINY, 7, of(), GENERATE_PLATE | DISABLE_REPLICATION | NO_WORKING | NO_SMELTING | NO_SMASHING | GENERATE_FRAME | GENERATE_ROD, null, 13100);
    public static IngotMaterial CosmicNeutronium = new IngotMaterial(671,"cosmic_neutronium",0x323232,MaterialIconSet.SHINY,7,of(new MaterialStack(Neutronium, 1)), GA_CORE_METAL | DISABLE_DECOMPOSITION,null,14100);
    public static SimpleFluidMaterial Catalase = new SimpleFluidMaterial("catalase", 0xdb6596, "?");
    public static SimpleFluidMaterial Blood = new SimpleFluidMaterial("blood", 0x5c0606, "Blood");
    public static SimpleFluidMaterial BloodCells = new SimpleFluidMaterial("blood_cells", 0xad2424, "???");
    public static SimpleFluidMaterial BloodPlasma = new SimpleFluidMaterial("blood_plasma", 0xe37171, "???");
    public static SimpleFluidMaterial BFGF = new SimpleFluidMaterial("bfgf", 0xb365e0, "bFGF");
    public static SimpleFluidMaterial BacterialGrowthMedium = new SimpleFluidMaterial("bacterial_growth_medium", 0x0b2e12, "For Bacteria");
    public static SimpleFluidMaterial DepletedGrowthMedium = new SimpleFluidMaterial("depleted_growth_medium", 0x071209, "Depleted");
    public static SimpleFluidMaterial AnimalCells = new SimpleFluidMaterial("animal_cells", 0xc94996, "???");
    public static SimpleFluidMaterial RapidlyReplicatingAnimalCells = new SimpleFluidMaterial("rapidly_replicating_animal_cells", 0x7a335e, TextFormatting.OBFUSCATED + "????");
    public static SimpleFluidMaterial MycGene = new SimpleFluidMaterial("myc_gene", 0x445724, "?");
    public static SimpleFluidMaterial Oct4Gene = new SimpleFluidMaterial("oct_4_gene", 0x374f0d, "?");
    public static SimpleFluidMaterial SOX2Gene = new SimpleFluidMaterial("sox_2_gene", 0x5d8714, "?");
    public static SimpleFluidMaterial KFL4Gene = new SimpleFluidMaterial("kfl_4_gene", 0x759143, "?");
    public static SimpleFluidMaterial Cas9 = new SimpleFluidMaterial("cas_9", 0x5f6e46, "?");
    public static SimpleFluidMaterial GenePlasmids = new SimpleFluidMaterial("pluripotency_induction_gene_plasmids", 0xabe053, "?");
    public static SimpleFluidMaterial Chitin = new SimpleFluidMaterial("chitin", 0xcbd479, "?");
    public static SimpleFluidMaterial Chitosan = new SimpleFluidMaterial("chitosan", 0xb1bd42, "?");
    public static SimpleFluidMaterial GeneTherapyFluid = new SimpleFluidMaterial("pluripotency_induction_gene_therapy_fluid", 0x6b2f66, "?");
    public static SimpleFluidMaterial Resin = new SimpleFluidMaterial("resin", 0x3d2f11, "?");
    public static SimpleFluidMaterial Brine = new SimpleFluidMaterial("brine", 0xfcfc8a, "?");
    public static SimpleFluidMaterial ZrHfSeparationMix = new SimpleFluidMaterial("zrhf_separation_mix", 0xfcfc95, "?");
    public static SimpleFluidMaterial MetalRichSlagSlurry = new SimpleFluidMaterial("metal_slag_slurry", (Zinc.materialRGB-10), "?");
    public static SimpleFluidMaterial PolyphenolMix = new SimpleFluidMaterial("polyphenol_mix", (Phenol.materialRGB+10), "?");
    public static SimpleFluidMaterial AcidifiedPolyphenolMix = new SimpleFluidMaterial("acidified_polyphenol_mix", (PolyphenolMix.rgb+SulfuricAcid.materialRGB)/2, "?");
    public static SimpleFluidMaterial Amidoxime = new SimpleFluidMaterial("amidoxime", 0x66ff33, "?");
    public static SimpleFluidMaterial DebrominatedWater = new SimpleFluidMaterial("debrominated_brine", 0x0000ff, WATER.formula());
    public static SimpleFluidMaterial SeaWater = new SimpleFluidMaterial("sea_water", 0x0000FF, WATER.formula()+"?");
    public static SimpleFluidMaterial ConcentratedBrine = new SimpleFluidMaterial("concentrated_brine", 0xfcfc95, "?");
    public static SimpleFluidMaterial CalciumFreeBrine = new SimpleFluidMaterial("calcium_free_brine", 0xfcfca6, "?");
    public static SimpleFluidMaterial SodiumFreeBrine = new SimpleFluidMaterial("sodium_free_brine", 0xfcfcb1, "?");
    public static SimpleFluidMaterial PotassiumFreeBrine = new SimpleFluidMaterial("potassium_free_brine", 0xfcfcbc, "?");
    public static SimpleFluidMaterial BoronFreeSolution = new SimpleFluidMaterial("boron_free_solution", 0xfcfccd, "?");
    public static SimpleFluidMaterial ChilledBrine = new SimpleFluidMaterial("chilled_brine", 0xfcfc95, "?");
    public static SimpleFluidMaterial Cycloparaphenylene = new SimpleFluidMaterial("cycloparaphenylene", 0x333333, "CPP");
    public static SimpleFluidMaterial NeutronPlasma = new SimpleFluidMaterial("neutron_plasma", 0xf0e9e9, "n");
    public static SimpleFluidMaterial QuassifissioningPlasma = new SimpleFluidMaterial("quasifissioning_plasma", 0xD5CB54, TextFormatting.OBFUSCATED + "???");
    public static SimpleFluidMaterial RubySlurry = new SimpleFluidMaterial("ruby_slurry", Ruby.materialRGB, "?");
    public static SimpleFluidMaterial SapphireSlurry = new SimpleFluidMaterial("sapphire_slurry", Sapphire.materialRGB, "?");
    public static SimpleFluidMaterial GreenSapphireSlurry = new SimpleFluidMaterial("green_sapphire_slurry", GreenSapphire.materialRGB, "?");
    public static SimpleFluidMaterial ATL = new SimpleFluidMaterial("atl", 0x709c4a, "ATL");
    public static SimpleFluidMaterial DrillingMud = new SimpleFluidMaterial("drilling_mud", 0x996600, "For the Void Miner");
    public static SimpleFluidMaterial UsedDrillingMud = new SimpleFluidMaterial("used_drilling_mud", 0x998833, "Used Mud");
    public static SimpleFluidMaterial UnprocessedNdYAGSolution = new SimpleFluidMaterial("unprocessed_ndyag_solution",0x6f20af, "Nd:YAG");
    public static SimpleFluidMaterial LiquidCrystalDetector = new SimpleFluidMaterial("liquid_crystal_detector",0xda20da);
    public static SimpleFluidMaterial QuarkGluonPlasma = new SimpleFluidMaterial("quark_gluon_plasma",0x8f00ff, TextFormatting.OBFUSCATED + "a" + TextFormatting.RESET + "(u2)d(c2)s(t2)bg" + TextFormatting.OBFUSCATED + "a", false, true);
    public static SimpleFluidMaterial HeavyQuarks = new SimpleFluidMaterial("heavy_quarks",0x008800, TextFormatting.OBFUSCATED + "a" + TextFormatting.RESET + "(u2)ds" + TextFormatting.OBFUSCATED + "a", false, true);
    public static SimpleFluidMaterial LightQuarks = new SimpleFluidMaterial("light_quarks",0x0000ff, TextFormatting.OBFUSCATED + "a" + TextFormatting.RESET + "(c2)(t2)b" + TextFormatting.OBFUSCATED + "a", false, true);
    public static SimpleFluidMaterial Gluons = new SimpleFluidMaterial("gluons",0xfcfcfa, TextFormatting.OBFUSCATED + "a" + TextFormatting.RESET + "g" + TextFormatting.OBFUSCATED + "a", false, true);
    public static SimpleFluidMaterial HeavyLeptonMix = new SimpleFluidMaterial("heavy_lepton_mix",0x5adf52, TextFormatting.OBFUSCATED + "a" + TextFormatting.RESET + "(t2)u" + TextFormatting.OBFUSCATED + "a", false, true);
    public static SimpleFluidMaterial CosmicComputingMix = new SimpleFluidMaterial("cosmic_computing_mix",0xafad2f, TextFormatting.OBFUSCATED + "aaaaa", false, true);
    public static SimpleFluidMaterial HeavyQuarkEnrichedMix = new SimpleFluidMaterial("heavy_quark_enriched_mix",0xefefef, TextFormatting.OBFUSCATED + "a" + TextFormatting.RESET + "(u2)d(c2)s(t2)b" + TextFormatting.OBFUSCATED + "a", false, true);
    public static SimpleFluidMaterial DenseNeutronPlasma = new SimpleFluidMaterial("dense_neutron_plasma",0xacecac,1000000, false, TextFormatting.OBFUSCATED.toString() + "a" + TextFormatting.RESET + TextFormatting.GRAY + "n" + TextFormatting.OBFUSCATED.toString() + "a");
    public static SimpleFluidMaterial CosmicMeshPlasma = new SimpleFluidMaterial("cosmic_mesh_plasma",0x1c1c8c,1000000, false, TextFormatting.OBFUSCATED.toString() + "nn");
    public static SimpleFluidMaterial FreeAlphaGas = new SimpleFluidMaterial("free_alpha_gas", 0xe0d407, "a");
    public static SimpleFluidMaterial FreeElectronGas = new SimpleFluidMaterial("free_electron_gas", 0x044c4c, "e-");
    public static SimpleFluidMaterial HighEnergyQGP = new SimpleFluidMaterial("high_energy_qgp", 0x8f00ff, TextFormatting.OBFUSCATED + "a" + TextFormatting.RESET + "(u2)d(c2)s(t2)bg" + TextFormatting.OBFUSCATED + "a", false, true);
    public static SimpleFluidMaterial FermionicUUMatter = new SimpleFluidMaterial("fermionic_uu_matter", UUMatter.materialRGB / 3, TextFormatting.OBFUSCATED + "???");
    public static SimpleFluidMaterial BosonicUUMatter = new SimpleFluidMaterial("bosonic_uu_matter", UUMatter.materialRGB - FermionicUUMatter.rgb, TextFormatting.OBFUSCATED + "???");
    public static SimpleFluidMaterial Soap = new SimpleFluidMaterial("soap", 0xFFAE42, "?");
    public static SimpleFluidMaterial DeglyceratedSoap = new SimpleFluidMaterial("deglyceratedsoap", 0xFFAE41);
    public static SimpleDustMaterial Yeast = new SimpleDustMaterial("yeast", 0xf0e660, (short) 26, MaterialIconSet.ROUGH, "???");
    public static SimpleDustMaterial GreenAlgae = new SimpleDustMaterial("green_algae", 0x228b22, (short) 32, MaterialIconSet.METALLIC, "An Algae");
    public static SimpleDustMaterial BrownAlgae = new SimpleDustMaterial("brown_algae", 0xa52a2a, (short) 33, MaterialIconSet.METALLIC, "An Algae");
    public static SimpleDustMaterial RedAlgae = new SimpleDustMaterial("red_algae", 0xf08080, (short) 34, MaterialIconSet.METALLIC, "An Algae");
    public static SimpleDustMaterial DryRedAlgae = new SimpleDustMaterial("dry_red_algae", 0xff7f50, (short) 35, MaterialIconSet.ROUGH, "A Dry Algae");
    public static SimpleDustMaterial RedAlgaePowder = new SimpleDustMaterial("red_algae_powder", 0xcc2f2f, (short) 36, MaterialIconSet.ROUGH, "A Powdered Algae");
    public static SimpleDustMaterial PreFreezeAgar = new SimpleDustMaterial("pre_freeze_agar", 0x132b0d, (short) 37, MaterialIconSet.ROUGH, "Warm Agar");
    public static SimpleDustMaterial FrozenAgarCrystals = new SimpleDustMaterial("frozen_agar_crystals", 0x68db4b, (short) 38, MaterialIconSet.SHINY, "Cold Agar");
    public static SimpleDustMaterial BrevibacteriumFlavium = new SimpleDustMaterial("brevibacterium_flavium", 0x2c4d24, (short) 40, MaterialIconSet.ROUGH, "Bacteria");
    public static SimpleDustMaterial StreptococcusPyogenes = new SimpleDustMaterial("streptococcus_pyogenes", 0x1c3b15, (short) 41, MaterialIconSet.ROUGH, "Bacteria");
    public static SimpleDustMaterial EschericiaColi = new SimpleDustMaterial("eschericia_coli", 0x2d4228, (short) 42, MaterialIconSet.ROUGH, "Bacteria");
    public static SimpleDustMaterial BifidobacteriumBreve = new SimpleDustMaterial("bifidobacterium_breve", 0x377528, (short) 43, MaterialIconSet.ROUGH, "Bacteria");
    public static SimpleDustMaterial Alumina = new SimpleDustMaterial("alumina", 0x0b585c, (short) 44, MaterialIconSet.ROUGH, "Al2O3");
    public static SimpleDustMaterial CupriavidusNecator = new SimpleDustMaterial("cupriavidus_necator", 0x22704f, (short) 46, MaterialIconSet.ROUGH, "Bacteria");
    public static SimpleDustMaterial Shewanella = new SimpleDustMaterial("shewanella", 0x8752ab, (short) 47, MaterialIconSet.METALLIC, "Bacteria");
    public static SimpleDustMaterial ZincResidualSlag = new SimpleDustMaterial("zinc_residual_slag", (Zinc.materialRGB-20), (short) 122, MaterialIconSet.DULL, "?");
    public static SimpleDustMaterial ZincFlueDust = new SimpleDustMaterial("zinc_flue_dust", 0xfcfca, (short) 123, MaterialIconSet.ROUGH, "?");
    public static SimpleDustMaterial FineZincSlagDust = new SimpleDustMaterial("fine_zinc_slag_dust", (Zinc.materialRGB-10), (short) 125, MaterialIconSet.FINE, "?");
    public static SimpleDustMaterial DehydrogenationCatalyst = new SimpleDustMaterial("dehydrogenation_catalyst", 0x6464f5, (short) 148, MaterialIconSet.SHINY, "?");
    public static SimpleDustMaterial NeodymiumDopedYttrium = new SimpleDustMaterial("neodymium_doped_yttrium",YttriumOxide.materialRGB,(short) 268,MaterialIconSet.DULL, "Nd:Y?");
    public static SimpleDustMaterial NdYAGNanoparticles = new SimpleDustMaterial("nd_yag_nanoparticles",0x6f20af,(short) 269,MaterialIconSet.SHINY, "Nd:YAG");
    public static SimpleDustMaterial PotassiumPermanganate = new SimpleDustMaterial("potassium_permanganate",PotassiumManganate.rgb-15,(short) 270,MaterialIconSet.ROUGH, "KMnO4");
    public static wSimpleDustMaterial PrHoYLFNanoparticles = new SimpleDustMaterial("prho_ylf_nanoparticles",0xcf8acf,(short) 278,MaterialIconSet.SHINY, "Pr/Ho:YLF");
    public static SimpleDustMaterial LuTmYVONanoparticles = new SimpleDustMaterial("lutm_yvo_nanoparticles",0x206faf,(short) 279,MaterialIconSet.SHINY, "Lu/Tm:YVO");
    public static SimpleDustMaterial UnprocessedNdYAGDust = new SimpleDustMaterial("unprocessed_ndyag_dust",0x6f20af,(short) 283,MaterialIconSet.DULL, "Nd:YAG?");
    public static SimpleDustMaterial LuTmYVOPrecipitate = new SimpleDustMaterial("lutm_yvo_precipitate",0xcf8acf,(short) 318,MaterialIconSet.DULL, "Lu/Tm:YVO?");
    public static SimpleDustMaterial SelectivelyMutatedCupriavidiusNecator = new SimpleDustMaterial("selectively_mutated_cupriavidius_necator", CupriavidusNecator.rgb * 5 / 4, (short) 373, MaterialIconSet.SHINY, "Bacteria");
    public static SimpleDustMaterial CoAcABCatalyst = new SimpleDustMaterial("coacab_catalyst", 0x755f30, (short) 900, MaterialIconSet.FINE, "Co/AC-AB");
    public static Material DrillingMudMixture = new Material.Builder(18504, "drilling_mud_mixture").fluid().color(CaCBaSMixture.rgb + LubricantClaySlurry.rgb).build();

    @Override
    public void onMaterialsInit() {

        /*
         * Element Materials, IDs 3000-3499
         */
        GAElementMaterials.register();

        /*
         * First Degree Materials, IDs 3500-6499
         */
        GAFirstDegreeMaterials.register();

        /*
         * Organic Chem Materials, IDs 6500-9499
         */
        GAOrganicChemistryMaterials.register();

        /*
         * Unknown Composition Materials, IDs 9500-11499
         */
        GAUnknownCompositionMaterials.register();

        /*
         * Second Degree Materials, IDs 11500-14499
         */
        GASecondDegreeMaterials.register();

        /*
         * Third Degree Materials, IDs 15500-18499
         */
        GAThirdDegreeMaterials.register();

        /*
         * High Degree Materials, IDs 18500-19999
         */
        GAHighDegreeMaterials.register();


        initNuclearMaterial();
        initOres();

        // Pipes
        Enderium.setFluidPipeProperties(650, 1500, true);
        Zeron100.setFluidPipeProperties(1750, 15000, true);
        Lafium.setFluidPipeProperties(2000, 23000, true);

        // Cables
        MVSuperconductorBase.setCableProperties(128, 4, 2);
        HVSuperconductorBase.setCableProperties(512, 4, 2);
        EVSuperconductorBase.setCableProperties(2048, 4, 2);
        IVSuperconductorBase.setCableProperties(8192, 4, 2);
        LuVSuperconductorBase.setCableProperties(32768, 4, 2);
        ZPMSuperconductorBase.setCableProperties(131072, 4, 2);
        UVSuperconductorBase.setCableProperties(524288, 4, 2);

        /* TODO
        MVSuperconductor.setCableProperties(128, 4, 0);
        ignoreCable(MVSuperconductor);
        HVSuperconductor.setCableProperties(512, 4, 0);
        ignoreCable(HVSuperconductor);
        EVSuperconductor.setCableProperties(2048, 4, 0);
        ignoreCable(EVSuperconductor);
        IVSuperconductor.setCableProperties(8192, 4, 0);
        ignoreCable(IVSuperconductor);
        LuVSuperconductor.setCableProperties(32768, 4, 0);
        ignoreCable(LuVSuperconductor);
        ZPMSuperconductor.setCableProperties(131072, 4, 0);
        ignoreCable(ZPMSuperconductor);
        UVSuperconductor.setCableProperties(524288, 4, 0);
        ignoreCable(UVSuperconductor);
        ignoreCable(UHVSuperconductor);
        ignoreCable(UEVSuperconductor);
        ignoreCable(UIVSuperconductor);
        ignoreCable(UMVSuperconductor);
        ignoreCable(UXVSuperconductor);

        addCableAboveGTCELimit(UHVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UHV], 4, 2));
        addCableAboveGTCELimit(UEVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UEV], 4, 2));
        addCableAboveGTCELimit(UIVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UIV], 4, 2));
        addCableAboveGTCELimit(UMVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UMV], 4, 2));
        addCableAboveGTCELimit(UXVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UXV], 4, 2));
        addCableAboveGTCELimit(TungstenTitaniumCarbide, new WireProperties(GAValues.V[GAValues.UHV], 4, 16));
        addCableAboveGTCELimit(AbyssalAlloy, new WireProperties(GAValues.V[GAValues.UHV], 2, 8));
        addCableAboveGTCELimit(EnrichedNaquadahAlloy, new WireProperties(GAValues.V[GAValues.UHV], 1, 4));
        addCableAboveGTCELimit(Pikyonium, new WireProperties(GAValues.V[GAValues.UEV], 4, 32));
        addCableAboveGTCELimit(TitanSteel, new WireProperties(GAValues.V[GAValues.UEV], 2, 16));
        addCableAboveGTCELimit(Cinobite, new WireProperties(GAValues.V[GAValues.UIV], 4, 64));
        addCableAboveGTCELimit(BlackTitanium, new WireProperties(GAValues.V[GAValues.UIV], 2, 32));
        addCableAboveGTCELimit(Neutronium, new WireProperties(GAValues.V[GAValues.UMV], 2, 32));
        addCableAboveGTCELimit(UHVSuperconductor, new WireProperties(GAValues.V[GAValues.UHV], 4, 0));
        addCableAboveGTCELimit(UEVSuperconductor, new WireProperties(GAValues.V[GAValues.UEV], 4, 0));
        addCableAboveGTCELimit(UIVSuperconductor, new WireProperties(GAValues.V[GAValues.UIV], 4, 0));
        addCableAboveGTCELimit(UMVSuperconductor, new WireProperties(GAValues.V[GAValues.UMV], 4, 0));
        addCableAboveGTCELimit(UXVSuperconductor, new WireProperties(GAValues.V[GAValues.UXV], 4, 0));
        */

        // Disable Mixer Flag
        YttriumBariumCuprate.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        GalliumArsenide.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        Polyethylene.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        Polytetrafluoroethylene.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        TungstenCarbide.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);

        // Plasmas
        Radon.addFlag(GENERATE_PLASMA);
        Potassium.addFlag(GENERATE_PLASMA);
        Carbon.addFlag(GENERATE_PLASMA);
        Magnesium.addFlag(GENERATE_PLASMA);
        Silicon.addFlag(GENERATE_PLASMA);
        Sulfur.addFlag(GENERATE_PLASMA);
        Argon.addFlag(GENERATE_PLASMA);
        Calcium.addFlag(GENERATE_PLASMA);
        Titanium.addFlag(GENERATE_PLASMA);

        // Decomposition
        Barite.addFlag(DISABLE_DECOMPOSITION);
        TungstenCarbide.addFlag(DISABLE_DECOMPOSITION);
        Uraninite.addFlag(DISABLE_DECOMPOSITION);
        NaquadahAlloy.addFlag(DISABLE_DECOMPOSITION);
        Trona.addFlag(DISABLE_DECOMPOSITION);
        Columbite.addFlag(DISABLE_DECOMPOSITION);
        Tantalite.addFlag(DISABLE_DECOMPOSITION);
        if (GAConfig.Misc.tungstenProcess) {
            Scheelite.addFlag(DISABLE_DECOMPOSITION);
            Tungstate.addFlag(DISABLE_DECOMPOSITION);
        }

        // Fine Wires
        Plutonium.addFlag(GENERATE_FINE_WIRE);

        // Long Rods
        Uranium.addFlag(GENERATE_LONG_ROD);

        // Core Metal
        Tritanium.addFlag(GA_CORE_METAL);
        Arsenic.addFlag(SMELT_INTO_FLUID);
        Duranium.addFlag(GA_CORE_METAL);

        // Replication
        Naquadria.addFlag(DISABLE_REPLICATION);
        Naquadah.addFlag(DISABLE_REPLICATION);
        NaquadahEnriched.addFlag(DISABLE_REPLICATION);

        // Prefix Ignores
        OrePrefix.block.setIgnored(Pyrotheum);
        OrePrefix.block.setIgnored(Cryotheum);
        OrePrefix.block.setIgnored(Snow);
        OrePrefix.block.setIgnored(MagnetoResonatic);
        OrePrefix.block.setIgnored(PotassiumDisulfate);
        OrePrefix.block.setIgnored(SodiumPotassiumAlloy);
        OrePrefix.block.setIgnored(FLiNaK);
        OrePrefix.block.setIgnored(FLiBe);
        OrePrefix.block.setIgnored(LeadBismuthEutectic);
        OrePrefix.block.setIgnored(RutheniumTetroxide);
        OrePrefix.dust.setIgnored(Snow);
        OrePrefix.dustSmall.setIgnored(Snow);
        OrePrefix.dustTiny.setIgnored(Snow);

        for (Material material : Material.MATERIAL_REGISTRY) {
            if (material instanceof IngotMaterial && ((IngotMaterial) material).toolSpeed > 0) {
                material.addFlag(GENERATE_DENSE);
            }
        }
    }

    private static void initOres() {

        // Ores
        Tellurium.addFlag(GENERATE_ORE);
        Diatomite.addFlag(GENERATE_ORE);
        GarnetSand.addFlag(GENERATE_ORE);
        Mica.addFlag(GENERATE_ORE);
        Asbestos.addFlag(GENERATE_ORE);
        Kyanite.addFlag(GENERATE_ORE);
        Pollucite.addFlag(GENERATE_ORE);
        BasalticMineralSand.addFlag(GENERATE_ORE);
        GraniticMineralSand.addFlag(GENERATE_ORE);
        FullersEarth.addFlag(GENERATE_ORE);
        Gypsum.addFlag(GENERATE_ORE);
        Zeolite.addFlag(GENERATE_ORE);
        Kaolinite.addFlag(GENERATE_ORE);
        Dolomite.addFlag(GENERATE_ORE);
        Wollastonite.addFlag(GENERATE_ORE);
        Trona.addFlag(GENERATE_ORE);
        Andradite.addFlag(GENERATE_ORE);
        Vermiculite.addFlag(GENERATE_ORE);
        Alunite.addFlag(GENERATE_ORE);
        GlauconiteSand.addFlag(GENERATE_ORE);
        Niter.addFlag(GENERATE_ORE);

        // Direct Smelting
        BasalticMineralSand.setDirectSmelting(Iron);
        GraniticMineralSand.setDirectSmelting(Iron);
        Cooperite.disableDirectSmelting = true;

        // Ore Multiplier
        PreciousMetal.setOreMultiplier(2);
        PlatinumMetallicPowder.setOreMultiplier(2);
        PalladiumMetallicPowder.setOreMultiplier(2);
        Trona.setOreMultiplier(2);
        Lepidolite.setOreMultiplier(2);
        Barytocalcite.setOreMultiplier(2);

        // Washed In
        PlatinumMetallicPowder.washedIn = SodiumPersulfate;
        RarestMetalResidue.washedIn = SodiumPersulfate;
        IrMetalResidue.washedIn = SodiumPersulfate;
        Witherite.washedIn = SodiumPersulfate;

        // Byproducts
        Salt.addOreByProducts(Borax);
        RockSalt.addOreByProducts(Borax);
        Lepidolite.addOreByProducts(Boron);
        Zirkelite.addOreByProducts(Thorium, Zirconium, Cerium);
        Caliche.addOreByProducts(Niter, Saltpeter, Lepidolite);
        Zircon.addOreByProducts(Cobalt, Lead, UraniumRadioactive.getMaterial());
        PreciousMetal.addOreByProducts(Lead, Silver, Nickel);
        Pyrochlore.addOreByProducts(Apatite, Calcite, Niobium);
        Uranium.addOreByProducts(Lead, UraniumRadioactive.getMaterial(), Thorium);
        Alunite.addOreByProducts(Zinc, Gallium, Iron);
        Fluorite.addOreByProducts(Calcium);
        FluoroApatite.addOreByProducts(Apatite, Fluorite, Phosphorus);
        BandedIron.addOreByProducts(Magnetite, Calcium, Magnesium, SiliconDioxide);
        Soapstone.addOreByProducts(SiliconDioxide, Magnesium, Calcite, Talc);
        Dolomite.addOreByProducts(Dolomite, Calcium, Magnesium);
        Wollastonite.addOreByProducts(Calcite, SiliconDioxide, Calcite, SiliconDioxide);
        Kyanite.addOreByProducts(Talc, Aluminium, Silicon);
        Kaolinite.addOreByProducts(Clay, Clay, SiliconDioxide, Kaolinite);
        Gypsum.addOreByProducts(Sulfur, Calcite, Salt);
        Talc.addOreByProducts(Clay, Clay, Carbon);
        Wulfenite.addOreByProducts(Iron, Manganese, Manganese, Lead);
        Powellite.addOreByProducts(Iron, Molybdenite, Potassium);
        Trona.addOreByProducts(Sodium, SodaAsh, SodaAsh);
        Mica.addOreByProducts(Potassium, Aluminium, Fluorite);
        Prasiolite.addOreByProducts(Prasiolite, Iron, SiliconDioxide);
        Saltpeter.addOreByProducts(Salt, Potassium);
        Rhodochrosite.addOreByProducts(Calcium, Manganese);
        Zeolite.addOreByProducts(Calcium, Silicon, Aluminium);
        Columbite.addOreByProducts(Iron, Manganese, Niobium);
        Barytocalcite.addOreByProducts(Calcite, Magnesium, Barite);
        Witherite.addOreByProducts(Calcite, Barite, Lead);
        Arsenopyrite.addOreByProducts(Iron, Cobaltite, Cobalt);
        Gallite.addOreByProducts(Sulfur, Copper, Copper, Gallium);
        Celestine.addOreByProducts(Gypsum, Calcite, Calcite, Strontium);
        Bowieite.addOreByProducts(Nickel, PlatinumMetallicPowder, RarestMetalResidue, CrudeRhodiumMetal);
        EnrichedNaquadricCompound.addOreByProducts(NaquadricCompound, NaquadriaticCompound);
        NaquadricCompound.addOreByProducts(EnrichedNaquadricCompound);
        PlatinumMetallicPowder.addOreByProducts(Nickel, IrMetalResidue, RarestMetalResidue, PlatinumMetallicPowder);
        RarestMetalResidue.addOreByProducts(IrMetalResidue, IrMetalResidue, IrMetalResidue, RarestMetalResidue);
        IrMetalResidue.addOreByProducts(PlatinumMetallicPowder, RarestMetalResidue);

        // Byproduct Overrides
        Bornite.oreByProducts.clear();
        Bornite.addOreByProducts(Pyrite, Cobalt, Cadmium, PreciousMetal);

        Chalcopyrite.oreByProducts.clear();
        Chalcopyrite.addOreByProducts(Pyrite, Cobalt, Cadmium, PreciousMetal);

        Copper.oreByProducts.clear();
        Copper.addOreByProducts(Cobalt, PreciousMetal, Nickel);

        Glowstone.oreByProducts.clear();
        Glowstone.addOreByProducts(Redstone, PreciousMetal);

        Magnetite.oreByProducts.clear();
        Magnetite.addOreByProducts(Iron, PreciousMetal);

        Pitchblende.oreByProducts.clear();
        Pitchblende.addOreByProducts(Thorium, UraniumRadioactive.getMaterial(), Lead);

        Nickel.oreByProducts.clear();
        Nickel.addOreByProducts(Cobalt, PlatinumMetallicPowder, Iron);

        Iridium.oreByProducts.clear();
        Iridium.addOreByProducts(PlatinumMetallicPowder, RarestMetalResidue);

        Platinum.oreByProducts.clear();
        Platinum.addOreByProducts(Nickel, IrMetalResidue);

        Osmium.oreByProducts.clear();
        Osmium.addOreByProducts(IrMetalResidue);

        Cooperite.oreByProducts.clear();
        Cooperite.addOreByProducts(PalladiumMetallicPowder, Nickel, IrMetalResidue);
    }

    private static void initNuclearMaterial() {
        ThoriumRadioactive.complexity = 100;
        Protactinium.complexity = 100;
        UraniumRadioactive.complexity = 100;
        Neptunium.complexity = 115;
        PlutoniumRadioactive.complexity = 120;
        AmericiumRadioactive.complexity = 135;
        Curium.complexity = 145;
        Berkelium.complexity = 150;
        Californium.complexity = 160;
        Einsteinium.complexity = 170;
        Fermium.complexity = 185;
        Mendelevium.complexity = 200;

        Thorium.addFlag(GENERATE_LONG_ROD);
        Uranium235.addFlag(GENERATE_LONG_ROD);

        Thorium232Isotope.fertile = true;
        Thorium232Isotope.isotopeDecay.put(Thorium233, 100);
        Thorium232Isotope.isotopeDecay.put(Protactinium233, 1000);
        Thorium232Isotope.isotopeDecay.put(Uranium233, 8900);

        Thorium233.isotopeDecay.put(Protactinium233, 9000);

        Protactinium233.isotopeDecay.put(Uranium233, 9000);

        //Uranium
        UraniumRadioactive.composition.put(Uranium238Isotope, 9890);
        UraniumRadioactive.composition.put(Uranium235Isotope, 100);
        UraniumRadioactive.composition.put(Uranium234, 10);

        Uranium233.fissile = true;
        Uranium235Isotope.fissile = true;
        Uranium234.fertile = true;
        Uranium238Isotope.fertile = true;

        Uranium235Isotope.baseHeat = 10;
        Uranium233.baseHeat = 7;

        Uranium234.isotopeDecay.put(Uranium235Isotope, 9000);
        Uranium238Isotope.isotopeDecay.put(Uranium239, 100);
        Uranium238Isotope.isotopeDecay.put(Neptunium239, 1000);
        Uranium238Isotope.isotopeDecay.put(Plutonium239, 8900);
        Uranium239.isotopeDecay.put(Neptunium239, 9000);


        //neptunium
        Neptunium.composition.put(Neptunium235, 2000);
        Neptunium.composition.put(Neptunium237, 5000);
        Neptunium.composition.put(Neptunium239, 3000);

        Neptunium237.fissile = true;
        Neptunium237.baseHeat = 11;

        Neptunium237.isotopeDecay.put(Protactinium233, 9000);
        Neptunium239.isotopeDecay.put(Plutonium239, 9000);
        Neptunium235.isotopeDecay.put(Uranium235Isotope, 9000);

        //plutonium
        PlutoniumRadioactive.composition.put(Plutonium244Isotope, 9890);
        PlutoniumRadioactive.composition.put(Plutonium241Isotope, 100);
        PlutoniumRadioactive.composition.put(Plutonium240, 10);

        Plutonium241Isotope.fissile = true;
        Plutonium239.fissile = true;
        Plutonium240.fertile = true;
        Plutonium244Isotope.fertile = true;

        Plutonium241Isotope.baseHeat = 13;
        Plutonium239.baseHeat = 10;

        Plutonium240.isotopeDecay.put(Plutonium241Isotope, 9000);
        Plutonium244Isotope.isotopeDecay.put(Plutonium245, 100);
        Plutonium244Isotope.isotopeDecay.put(Americium245, 1000);
        Plutonium244Isotope.isotopeDecay.put(Curium245, 8900);
        Plutonium245.isotopeDecay.put(Americium245, 9000);

        //Americium
        AmericiumRadioactive.composition.put(Americium241, 2000);
        AmericiumRadioactive.composition.put(Americium243, 5000);
        AmericiumRadioactive.composition.put(Americium245, 3000);

        Americium243.fissile = true;
        Americium243.baseHeat = 14;

        Americium243.isotopeDecay.put(Neptunium239, 9000);
        Americium245.isotopeDecay.put(Curium245, 9000);
        Americium241.isotopeDecay.put(Plutonium241Isotope, 9000);

        //Curium
        Curium.composition.put(Curium250, 9890);
        Curium.composition.put(Curium247, 100);
        Curium.composition.put(Curium246, 10);

        Curium245.fissile = true;
        Curium247.fissile = true;
        Curium246.fertile = true;
        Curium250.fertile = true;

        Curium245.baseHeat = 13;
        Curium247.baseHeat = 16;

        Curium246.isotopeDecay.put(Curium247, 9000);
        Curium250.isotopeDecay.put(Curium251, 100);
        Curium250.isotopeDecay.put(Berkelium251, 1000);
        Curium250.isotopeDecay.put(Californium251, 8900);
        Curium251.isotopeDecay.put(Americium245, 9000);

        //Berkelium
        Berkelium.composition.put(Berkelium247, 2000);
        Berkelium.composition.put(Berkelium249, 5000);
        Berkelium.composition.put(Berkelium251, 3000);

        Berkelium249.fissile = true;
        Berkelium249.baseHeat = 17;

        Berkelium249.isotopeDecay.put(Americium245, 9000);
        Berkelium251.isotopeDecay.put(Californium251, 9000);
        Berkelium247.isotopeDecay.put(Curium247, 9000);

        //Californium
        Californium.composition.put(Californium252, 9890);
        Californium.composition.put(Californium253, 100);
        Californium.composition.put(Californium256, 10);

        Californium251.fissile = true;
        Californium253.fissile = true;
        Californium252.fertile = true;
        Californium256.fertile = true;

        Californium251.baseHeat = 16;
        Californium253.baseHeat = 19;

        Californium252.isotopeDecay.put(Californium253, 9000);
        Californium256.isotopeDecay.put(Californium257, 100);
        Californium256.isotopeDecay.put(Einsteinium257, 1000);
        Californium256.isotopeDecay.put(Fermium257, 8900);
        Californium257.isotopeDecay.put(Einsteinium257, 9000);

        //Einsteinium
        Einsteinium.composition.put(Einsteinium253, 2000);
        Einsteinium.composition.put(Einsteinium255, 5000);
        Einsteinium.composition.put(Einsteinium257, 3000);

        Einsteinium255.fissile = true;
        Einsteinium255.baseHeat = 20;

        Einsteinium255.isotopeDecay.put(Berkelium251, 9000);
        Einsteinium257.isotopeDecay.put(Fermium257, 9000);
        Einsteinium253.isotopeDecay.put(Californium253, 9000);


        //Fermium
        Fermium.composition.put(Fermium258, 9890);
        Fermium.composition.put(Fermium259, 100);
        Fermium.composition.put(Fermium262, 10);

        Fermium257.fissile = true;
        Fermium259.fissile = true;
        Fermium258.fertile = true;
        Fermium262.fertile = true;

        Fermium257.baseHeat = 19;
        Fermium259.baseHeat = 22;

        Fermium258.isotopeDecay.put(Fermium259, 9000);
        Fermium262.isotopeDecay.put(Fermium263, 1000);
        Fermium262.isotopeDecay.put(Mendelevium263, 9000);
        Fermium263.isotopeDecay.put(Mendelevium263, 9000);

        //Mendelevium
        Mendelevium.composition.put(Mendelevium259, 2000);
        Mendelevium.composition.put(Mendelevium261, 5000);
        Mendelevium.composition.put(Mendelevium263, 3000);

        Mendelevium261.fissile = true;
        Mendelevium261.baseHeat = 23;
        Mendelevium261.isotopeDecay.put(Einsteinium257, 9000);
        Mendelevium259.isotopeDecay.put(Fermium259, 9000);

    }
}
