package gregicadditions.materials;

import gregicadditions.GAConfig;
import gregtech.api.unification.material.info.MaterialFlag;
import gregtech.api.unification.material.properties.*;
import gregtech.api.unification.ore.OrePrefix;

import static gregicadditions.GAMaterials.*;
import static gregicadditions.materials.GAMaterialFlags.*;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.material.info.MaterialFlags.*;

public class GAMaterialFlagAddition {

    public static void init() {
        initGeneral();
        initOres();
        initNuclearMaterial();
    }

    private static void initGeneral() {
        /* TODO
        ignoreCable(UHVSuperconductor);
        ignoreCable(UEVSuperconductor);
        ignoreCable(UIVSuperconductor);
        ignoreCable(UMVSuperconductor);
        ignoreCable(UXVSuperconductor);

        addCableAboveGTCELimit(UHVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UHV], 4, 2));
        addCableAboveGTCELimit(UEVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UEV], 4, 2));
        addCableAboveGTCELimit(UIVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UIV], 4, 2));
        addCableAboveGTCELimit(UMVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UMV], 4, 2));
        addCableAboveGTCELimit(UXVSuperconductorBase, new WireProperties(GAValues.V[GAValues.UXV], 4, 2));
        addCableAboveGTCELimit(TungstenTitaniumCarbide, new WireProperties(GAValues.V[GAValues.UHV], 4, 16));
        addCableAboveGTCELimit(AbyssalAlloy, new WireProperties(GAValues.V[GAValues.UHV], 2, 8));
        addCableAboveGTCELimit(EnrichedNaquadahAlloy, new WireProperties(GAValues.V[GAValues.UHV], 1, 4));
        addCableAboveGTCELimit(Pikyonium, new WireProperties(GAValues.V[GAValues.UEV], 4, 32));
        addCableAboveGTCELimit(TitanSteel, new WireProperties(GAValues.V[GAValues.UEV], 2, 16));
        addCableAboveGTCELimit(Cinobite, new WireProperties(GAValues.V[GAValues.UIV], 4, 64));
        addCableAboveGTCELimit(BlackTitanium, new WireProperties(GAValues.V[GAValues.UIV], 2, 32));
        addCableAboveGTCELimit(Neutronium, new WireProperties(GAValues.V[GAValues.UMV], 2, 32));
        addCableAboveGTCELimit(UHVSuperconductor, new WireProperties(GAValues.V[GAValues.UHV], 4, 0));
        addCableAboveGTCELimit(UEVSuperconductor, new WireProperties(GAValues.V[GAValues.UEV], 4, 0));
        addCableAboveGTCELimit(UIVSuperconductor, new WireProperties(GAValues.V[GAValues.UIV], 4, 0));
        addCableAboveGTCELimit(UMVSuperconductor, new WireProperties(GAValues.V[GAValues.UMV], 4, 0));
        addCableAboveGTCELimit(UXVSuperconductor, new WireProperties(GAValues.V[GAValues.UXV], 4, 0));
        */

        // Disable Mixer Flag
        YttriumBariumCuprate.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        GalliumArsenide.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        Polyethylene.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        Polytetrafluoroethylene.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);
        TungstenCarbide.addFlag(DISABLE_AUTOGENERATED_MIXER_RECIPE);

        // Plasmas
        Radon.setProperty(PropertyKey.PLASMA, new PlasmaProperty());
        Carbon.setProperty(PropertyKey.PLASMA, new PlasmaProperty());
        Magnesium.setProperty(PropertyKey.PLASMA, new PlasmaProperty());
        Silicon.setProperty(PropertyKey.PLASMA, new PlasmaProperty());
        Sulfur.setProperty(PropertyKey.PLASMA, new PlasmaProperty());
        Argon.setProperty(PropertyKey.PLASMA, new PlasmaProperty());
        Calcium.setProperty(PropertyKey.PLASMA, new PlasmaProperty());
        Titanium.setProperty(PropertyKey.PLASMA, new PlasmaProperty());

        // Decomposition
        Barite.addFlag(DISABLE_DECOMPOSITION);
        TungstenCarbide.addFlag(DISABLE_DECOMPOSITION);
        Uraninite.addFlag(DISABLE_DECOMPOSITION);
        NaquadahAlloy.addFlag(DISABLE_DECOMPOSITION);
        Trona.addFlag(DISABLE_DECOMPOSITION);
        Columbite.addFlag(DISABLE_DECOMPOSITION);
        Tantalite.addFlag(DISABLE_DECOMPOSITION);
        if (GAConfig.Misc.tungstenProcess) {
            Scheelite.addFlag(DISABLE_DECOMPOSITION);
            Tungstate.addFlag(DISABLE_DECOMPOSITION);
        }

        //todo
        // Fine Wires
//        Plutonium.addFlag(GENERATE_FINE_WIRE);

        // Long Rods
//        Uranium.addFlag(GENERATE_LONG_ROD);

        // Core Metal
        Tritanium.addFlag(GA_CORE_METAL.toArray(new MaterialFlag[0]));
        Duranium.addFlag(GA_CORE_METAL.toArray(new MaterialFlag[0]));

        // Replication
        Naquadria.addFlag(DISABLE_REPLICATION);
        Naquadah.addFlag(DISABLE_REPLICATION);
        NaquadahEnriched.addFlag(DISABLE_REPLICATION);

        // Prefix Ignores
        OrePrefix.block.setIgnored(Pyrotheum);
        OrePrefix.block.setIgnored(Cryotheum);

        // Fluids
        Arsenic.setProperty(PropertyKey.FLUID, new FluidProperty());
    }

    private static void initOres() {

        // Ores
        Tellurium.setProperty(PropertyKey.ORE, new OreProperty());
        Diatomite.setProperty(PropertyKey.ORE, new OreProperty());
        GarnetSand.setProperty(PropertyKey.ORE, new OreProperty());
        Mica.setProperty(PropertyKey.ORE, new OreProperty());
        Asbestos.setProperty(PropertyKey.ORE, new OreProperty());
        Kyanite.setProperty(PropertyKey.ORE, new OreProperty());
        Pollucite.setProperty(PropertyKey.ORE, new OreProperty());
        BasalticMineralSand.setProperty(PropertyKey.ORE, new OreProperty());
        GraniticMineralSand.setProperty(PropertyKey.ORE, new OreProperty());
        FullersEarth.setProperty(PropertyKey.ORE, new OreProperty());
        Gypsum.setProperty(PropertyKey.ORE, new OreProperty());
        Zeolite.setProperty(PropertyKey.ORE, new OreProperty());
        Kaolinite.setProperty(PropertyKey.ORE, new OreProperty());
        Dolomite.setProperty(PropertyKey.ORE, new OreProperty());
        Wollastonite.setProperty(PropertyKey.ORE, new OreProperty());
        Trona.setProperty(PropertyKey.ORE, new OreProperty());
        Andradite.setProperty(PropertyKey.ORE, new OreProperty());
        Vermiculite.setProperty(PropertyKey.ORE, new OreProperty());
        Alunite.setProperty(PropertyKey.ORE, new OreProperty());
        GlauconiteSand.setProperty(PropertyKey.ORE, new OreProperty());
        Niter.setProperty(PropertyKey.ORE, new OreProperty());

        // Direct Smelting todo in CEu
        BasalticMineralSand.setDirectSmelting(Iron);
        GraniticMineralSand.setDirectSmelting(Iron);
        Cooperite.disableDirectSmelting = true;

        // Ore Multiplier
        PreciousMetal.setProperty(PropertyKey.ORE, new OreProperty(2, 1));
        PlatinumMetallicPowder.setProperty(PropertyKey.ORE, new OreProperty(2, 1));
        PalladiumMetallicPowder.setProperty(PropertyKey.ORE, new OreProperty(2, 1));
        Trona.setProperty(PropertyKey.ORE, new OreProperty(2, 1));
        Lepidolite.setProperty(PropertyKey.ORE, new OreProperty(2, 1));
        Barytocalcite.setProperty(PropertyKey.ORE, new OreProperty(2, 1));

        // Washed In
        OreProperty property = new OreProperty();
        property.setWashedIn(SodiumPersulfate);
        PlatinumMetallicPowder.setProperty(PropertyKey.ORE, property);
        RarestMetalResidue.setProperty(PropertyKey.ORE, property);
        IrMetalResidue.setProperty(PropertyKey.ORE, property);
        Witherite.setProperty(PropertyKey.ORE, property);

        // Byproducts todo in CEu
        Salt.addOreByProducts(Borax);
        RockSalt.addOreByProducts(Borax);
        Lepidolite.addOreByProducts(Boron);
        Zirkelite.addOreByProducts(Thorium, Zirconium, Cerium);
        Caliche.addOreByProducts(Niter, Saltpeter, Lepidolite);
        Zircon.addOreByProducts(Cobalt, Lead, Uranium238);
        PreciousMetal.addOreByProducts(Lead, Silver, Nickel);
        Pyrochlore.addOreByProducts(Apatite, Calcite, Niobium);
        Uranium238.addOreByProducts(Lead, Uranium238, Thorium);
        Alunite.addOreByProducts(Zinc, Gallium, Iron);
        Fluorite.addOreByProducts(Calcium);
        FluoroApatite.addOreByProducts(Apatite, Fluorite, Phosphorus);
        BandedIron.addOreByProducts(Magnetite, Calcium, Magnesium, SiliconDioxide);
        Soapstone.addOreByProducts(SiliconDioxide, Magnesium, Calcite, Talc);
        Dolomite.addOreByProducts(Dolomite, Calcium, Magnesium);
        Wollastonite.addOreByProducts(Calcite, SiliconDioxide, Calcite, SiliconDioxide);
        Kyanite.addOreByProducts(Talc, Aluminium, Silicon);
        Kaolinite.addOreByProducts(Clay, Clay, SiliconDioxide, Kaolinite);
        Gypsum.addOreByProducts(Sulfur, Calcite, Salt);
        Talc.addOreByProducts(Clay, Clay, Carbon);
        Wulfenite.addOreByProducts(Iron, Manganese, Manganese, Lead);
        Powellite.addOreByProducts(Iron, Molybdenite, Potassium);
        Trona.addOreByProducts(Sodium, SodaAsh, SodaAsh);
        Mica.addOreByProducts(Potassium, Aluminium, Fluorite);
        Saltpeter.addOreByProducts(Salt, Potassium);
        Rhodochrosite.addOreByProducts(Calcium, Manganese);
        Zeolite.addOreByProducts(Calcium, Silicon, Aluminium);
        Columbite.addOreByProducts(Iron, Manganese, Niobium);
        Barytocalcite.addOreByProducts(Calcite, Magnesium, Barite);
        Witherite.addOreByProducts(Calcite, Barite, Lead);
        Arsenopyrite.addOreByProducts(Iron, Cobaltite, Cobalt);
        Gallite.addOreByProducts(Sulfur, Copper, Copper, Gallium);
        Celestine.addOreByProducts(Gypsum, Calcite, Calcite, Strontium);
        Bowieite.addOreByProducts(Nickel, PlatinumMetallicPowder, RarestMetalResidue, CrudeRhodiumMetal);
        EnrichedNaquadricCompound.addOreByProducts(NaquadricCompound, NaquadriaticCompound);
        NaquadricCompound.addOreByProducts(EnrichedNaquadricCompound);
        PlatinumMetallicPowder.addOreByProducts(Nickel, IrMetalResidue, RarestMetalResidue, PlatinumMetallicPowder);
        RarestMetalResidue.addOreByProducts(IrMetalResidue, IrMetalResidue, IrMetalResidue, RarestMetalResidue);
        IrMetalResidue.addOreByProducts(PlatinumMetallicPowder, RarestMetalResidue);

        // Byproduct Overrides
        Bornite.oreByProducts.clear();
        Bornite.addOreByProducts(Pyrite, Cobalt, Cadmium, PreciousMetal);

        Chalcopyrite.oreByProducts.clear();
        Chalcopyrite.addOreByProducts(Pyrite, Cobalt, Cadmium, PreciousMetal);

        Copper.oreByProducts.clear();
        Copper.addOreByProducts(Cobalt, PreciousMetal, Nickel);

        Glowstone.oreByProducts.clear();
        Glowstone.addOreByProducts(Redstone, PreciousMetal);

        Magnetite.oreByProducts.clear();
        Magnetite.addOreByProducts(Iron, PreciousMetal);

        Pitchblende.oreByProducts.clear();
        Pitchblende.addOreByProducts(Thorium, UraniumRadioactive.getMaterial(), Lead);

        Nickel.oreByProducts.clear();
        Nickel.addOreByProducts(Cobalt, PlatinumMetallicPowder, Iron);

        Iridium.oreByProducts.clear();
        Iridium.addOreByProducts(PlatinumMetallicPowder, RarestMetalResidue);

        Platinum.oreByProducts.clear();
        Platinum.addOreByProducts(Nickel, IrMetalResidue);

        Osmium.oreByProducts.clear();
        Osmium.addOreByProducts(IrMetalResidue);

        Cooperite.oreByProducts.clear();
        Cooperite.addOreByProducts(PalladiumMetallicPowder, Nickel, IrMetalResidue);

        Triniite.addOreByProducts(NaquadricCompound, Bismuth, Thallium)
    }

    private static void initNuclearMaterial() {
        //todo
//        ThoriumRadioactive.complexity = 100;
//        Protactinium.complexity = 100;
//        UraniumRadioactive.complexity = 100;
//        Neptunium.complexity = 115;
//        PlutoniumRadioactive.complexity = 120;
//        AmericiumRadioactive.complexity = 135;
//        Curium.complexity = 145;
//        Berkelium.complexity = 150;
//        Californium.complexity = 160;
//        Einsteinium.complexity = 170;
//        Fermium.complexity = 185;
//        Mendelevium.complexity = 200;
//
//        Thorium.addFlag(GENERATE_LONG_ROD);
//        Uranium235.addFlag(GENERATE_LONG_ROD);
//
//        Thorium232.fertile = true;
//        Thorium232.isotopeDecay.put(Thorium233, 100);
//        Thorium232.isotopeDecay.put(Protactinium233, 1000);
//        Thorium232.isotopeDecay.put(Uranium233, 8900);
//
//        Thorium233.isotopeDecay.put(Protactinium233, 9000);
//
//        Protactinium233.isotopeDecay.put(Uranium233, 9000);
//
//        //Uranium
//        UraniumRadioactive.composition.put(Uranium238Isotope, 9890);
//        UraniumRadioactive.composition.put(Uranium235Isotope, 100);
//        UraniumRadioactive.composition.put(Uranium234, 10);
//
//        Uranium233.fissile = true;
//        Uranium235Isotope.fissile = true;
//        Uranium234.fertile = true;
//        Uranium238Isotope.fertile = true;
//
//        Uranium235Isotope.baseHeat = 10;
//        Uranium233.baseHeat = 7;
//
//        Uranium234.isotopeDecay.put(Uranium235Isotope, 9000);
//        Uranium238Isotope.isotopeDecay.put(Uranium239, 100);
//        Uranium238Isotope.isotopeDecay.put(Neptunium239, 1000);
//        Uranium238Isotope.isotopeDecay.put(Plutonium239, 8900);
//        Uranium239.isotopeDecay.put(Neptunium239, 9000);
//
//
//        //neptunium
//        Neptunium.composition.put(Neptunium235, 2000);
//        Neptunium.composition.put(Neptunium237, 5000);
//        Neptunium.composition.put(Neptunium239, 3000);
//
//        Neptunium237.fissile = true;
//        Neptunium237.baseHeat = 11;
//
//        Neptunium237.isotopeDecay.put(Protactinium233, 9000);
//        Neptunium239.isotopeDecay.put(Plutonium239, 9000);
//        Neptunium235.isotopeDecay.put(Uranium235Isotope, 9000);
//
//        //plutonium
//        PlutoniumRadioactive.composition.put(Plutonium244, 9890);
//        PlutoniumRadioactive.composition.put(Plutonium241Isotope, 100);
//        PlutoniumRadioactive.composition.put(Plutonium240, 10);
//
//        Plutonium241Isotope.fissile = true;
//        Plutonium239.fissile = true;
//        Plutonium240.fertile = true;
//        Plutonium244.fertile = true;
//
//        Plutonium241Isotope.baseHeat = 13;
//        Plutonium239.baseHeat = 10;
//
//        Plutonium240.isotopeDecay.put(Plutonium241Isotope, 9000);
//        Plutonium244.isotopeDecay.put(Plutonium245, 100);
//        Plutonium244.isotopeDecay.put(Americium245, 1000);
//        Plutonium244.isotopeDecay.put(Curium245, 8900);
//        Plutonium245.isotopeDecay.put(Americium245, 9000);
//
//        //Americium
//        AmericiumRadioactive.composition.put(Americium241, 2000);
//        AmericiumRadioactive.composition.put(Americium243, 5000);
//        AmericiumRadioactive.composition.put(Americium245, 3000);
//
//        Americium243.fissile = true;
//        Americium243.baseHeat = 14;
//
//        Americium243.isotopeDecay.put(Neptunium239, 9000);
//        Americium245.isotopeDecay.put(Curium245, 9000);
//        Americium241.isotopeDecay.put(Plutonium241Isotope, 9000);
//
//        //Curium
//        Curium.composition.put(Curium250, 9890);
//        Curium.composition.put(Curium247, 100);
//        Curium.composition.put(Curium246, 10);
//
//        Curium245.fissile = true;
//        Curium247.fissile = true;
//        Curium246.fertile = true;
//        Curium250.fertile = true;
//
//        Curium245.baseHeat = 13;
//        Curium247.baseHeat = 16;
//
//        Curium246.isotopeDecay.put(Curium247, 9000);
//        Curium250.isotopeDecay.put(Curium251, 100);
//        Curium250.isotopeDecay.put(Berkelium251, 1000);
//        Curium250.isotopeDecay.put(Californium251, 8900);
//        Curium251.isotopeDecay.put(Americium245, 9000);
//
//        //Berkelium
//        Berkelium.composition.put(Berkelium247, 2000);
//        Berkelium.composition.put(Berkelium249, 5000);
//        Berkelium.composition.put(Berkelium251, 3000);
//
//        Berkelium249.fissile = true;
//        Berkelium249.baseHeat = 17;
//
//        Berkelium249.isotopeDecay.put(Americium245, 9000);
//        Berkelium251.isotopeDecay.put(Californium251, 9000);
//        Berkelium247.isotopeDecay.put(Curium247, 9000);
//
//        //Californium
//        Californium.composition.put(Californium252, 9890);
//        Californium.composition.put(Californium253, 100);
//        Californium.composition.put(Californium256, 10);
//
//        Californium251.fissile = true;
//        Californium253.fissile = true;
//        Californium252.fertile = true;
//        Californium256.fertile = true;
//
//        Californium251.baseHeat = 16;
//        Californium253.baseHeat = 19;
//
//        Californium252.isotopeDecay.put(Californium253, 9000);
//        Californium256.isotopeDecay.put(Californium257, 100);
//        Californium256.isotopeDecay.put(Einsteinium257, 1000);
//        Californium256.isotopeDecay.put(Fermium257, 8900);
//        Californium257.isotopeDecay.put(Einsteinium257, 9000);
//
//        //Einsteinium
//        Einsteinium.composition.put(Einsteinium253, 2000);
//        Einsteinium.composition.put(Einsteinium255, 5000);
//        Einsteinium.composition.put(Einsteinium257, 3000);
//
//        Einsteinium255.fissile = true;
//        Einsteinium255.baseHeat = 20;
//
//        Einsteinium255.isotopeDecay.put(Berkelium251, 9000);
//        Einsteinium257.isotopeDecay.put(Fermium257, 9000);
//        Einsteinium253.isotopeDecay.put(Californium253, 9000);
//
//
//        //Fermium
//        Fermium.composition.put(Fermium258, 9890);
//        Fermium.composition.put(Fermium259, 100);
//        Fermium.composition.put(Fermium262, 10);
//
//        Fermium257.fissile = true;
//        Fermium259.fissile = true;
//        Fermium258.fertile = true;
//        Fermium262.fertile = true;
//
//        Fermium257.baseHeat = 19;
//        Fermium259.baseHeat = 22;
//
//        Fermium258.isotopeDecay.put(Fermium259, 9000);
//        Fermium262.isotopeDecay.put(Fermium263, 1000);
//        Fermium262.isotopeDecay.put(Mendelevium263, 9000);
//        Fermium263.isotopeDecay.put(Mendelevium263, 9000);
//
//        //Mendelevium
//        Mendelevium.composition.put(Mendelevium259, 2000);
//        Mendelevium.composition.put(Mendelevium261, 5000);
//        Mendelevium.composition.put(Mendelevium263, 3000);
//
//        Mendelevium261.fissile = true;
//        Mendelevium261.baseHeat = 23;
//        Mendelevium261.isotopeDecay.put(Einsteinium257, 9000);
//        Mendelevium259.isotopeDecay.put(Fermium259, 9000);

    }
}
