package gregicadditions.bees;

import forestry.core.ModuleCore;
import forestry.core.fluids.Fluids;
import gregicadditions.GAConfig;
import gregtech.api.recipes.RecipeMaps;
import gregtech.api.unification.OreDictUnifier;
import gregtech.api.unification.material.Materials;
import gregtech.api.unification.ore.OrePrefix;

public class GTMachineRecipes {
	public static void postInit() {
		//Impregnated Recipes
		if (GAConfig.GTBees.AssemblerRecipes) {
			RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder().EUt(8).duration(16).circuitMeta(1).input(OrePrefix.log, Materials.Wood, 8).fluidInputs(Fluids.SEED_OIL.getFluid(250)).outputs(ModuleCore.getItems().impregnatedCasing.getItemStack()).buildAndRegister();
			RecipeMaps.ASSEMBLER_RECIPES.recipeBuilder().EUt(16).duration(64).circuitMeta(8).input(OrePrefix.log, Materials.Wood).fluidInputs(Fluids.SEED_OIL.getFluid(50)).outputs(ModuleCore.getItems().stickImpregnated.getItemStack()).buildAndRegister();
		}

		//Non-generated Fluid Extractor Recipes
		RecipeMaps.FLUID_EXTRACTION_RECIPES.recipeBuilder().EUt(128).duration(256).inputs(ModuleCore.getItems().phosphor.getItemStack()).chancedOutput(OreDictUnifier.get(OrePrefix.dust, Materials.Phosphor), 1000, 1000).fluidOutputs(Materials.Lava.getFluid(800)).buildAndRegister();

		//Comb Autoclave Recipes
		if (GAConfig.GTBees.AutoclaverRecipes) {
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(1280).inputs(GTCombItem.getComb(GTCombs.LIGNITE, 16)).fluidInputs(Materials.UUMatter.getFluid(1)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lignite)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(3072).inputs(GTCombItem.getComb(GTCombs.COAL, 16)).fluidInputs(Materials.UUMatter.getFluid(3)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Coal)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(12544).inputs(GTCombItem.getComb(GTCombs.OIL, 16)).fluidInputs(Materials.UUMatter.getFluid(10)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Oilsands)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(2304).inputs(GTCombItem.getComb(GTCombs.STONE, 16)).fluidInputs(Materials.UUMatter.getFluid(2)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Soapstone)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(12544).inputs(GTCombItem.getComb(GTCombs.CERTUS, 16)).fluidInputs(Materials.UUMatter.getFluid(10)).outputs(OreDictUnifier.get(OrePrefix.dust, Materials.Cerium)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(10880).inputs(GTCombItem.getComb(GTCombs.REDSTONE, 16)).fluidInputs(Materials.UUMatter.getFluid(9)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Redstone)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(3584).inputs(GTCombItem.getComb(GTCombs.LAPIS, 16)).fluidInputs(Materials.UUMatter.getFluid(3)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lapis)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(3200).inputs(GTCombItem.getComb(GTCombs.RUBY, 16)).fluidInputs(Materials.UUMatter.getFluid(3)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Ruby)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(2560).inputs(GTCombItem.getComb(GTCombs.SAPPHIRE, 16)).fluidInputs(Materials.UUMatter.getFluid(2)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Sapphire)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(98300).inputs(GTCombItem.getComb(GTCombs.DIAMOND, 16)).fluidInputs(Materials.UUMatter.getFluid(77)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Diamond)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(3584).inputs(GTCombItem.getComb(GTCombs.OLIVINE, 16)).fluidInputs(Materials.UUMatter.getFluid(3)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Olivine)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(2304).inputs(GTCombItem.getComb(GTCombs.EMERALD, 16)).fluidInputs(Materials.UUMatter.getFluid(2)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Emerald)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(3584).inputs(GTCombItem.getComb(GTCombs.SLAG, 16)).fluidInputs(Materials.UUMatter.getFluid(3)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Salt)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(8064).inputs(GTCombItem.getComb(GTCombs.COPPON, 16)).fluidInputs(Materials.UUMatter.getFluid(7)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Copper)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(15104).inputs(GTCombItem.getComb(GTCombs.TINE, 16)).fluidInputs(Materials.UUMatter.getFluid(12)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Tin)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(26496).inputs(GTCombItem.getComb(GTCombs.PLUMBIA, 16)).fluidInputs(Materials.UUMatter.getFluid(21)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lead)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(7168).inputs(GTCombItem.getComb(GTCombs.FERRU, 16)).fluidInputs(Materials.UUMatter.getFluid(6)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Iron)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(7168).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 16)).fluidInputs(Materials.UUMatter.getFluid(6)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Iron)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(7424).inputs(GTCombItem.getComb(GTCombs.NICKELDUST, 16)).fluidInputs(Materials.UUMatter.getFluid(6)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Nickel)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(8320).inputs(GTCombItem.getComb(GTCombs.GALVANIA, 16)).fluidInputs(Materials.UUMatter.getFluid(7)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Zinc)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(13696).inputs(GTCombItem.getComb(GTCombs.ARGENTIA, 16)).fluidInputs(Materials.UUMatter.getFluid(11)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Silver)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(25088).inputs(GTCombItem.getComb(GTCombs.AURELIA, 16)).fluidInputs(Materials.UUMatter.getFluid(20)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Gold)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(3328).inputs(GTCombItem.getComb(GTCombs.BAUXIA, 16)).fluidInputs(Materials.UUMatter.getFluid(3)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Aluminium)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(7040).inputs(GTCombItem.getComb(GTCombs.PYROLUSIUM, 16)).fluidInputs(Materials.UUMatter.getFluid(6)).outputs(OreDictUnifier.get(OrePrefix.dust, Materials.Manganese)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(6144).inputs(GTCombItem.getComb(GTCombs.TITANIUM, 16)).fluidInputs(Materials.UUMatter.getFluid(5)).outputs(OreDictUnifier.get(OrePrefix.dust, Materials.Titanium)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(4736).inputs(GTCombItem.getComb(GTCombs.SCHEELINIUM, 16)).fluidInputs(Materials.UUMatter.getFluid(4)).outputs(OreDictUnifier.get(OrePrefix.dust, Materials.Tungsten)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(24960).inputs(GTCombItem.getComb(GTCombs.PLATINA, 16)).fluidInputs(Materials.UUMatter.getFluid(20)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Platinum)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(24576).inputs(GTCombItem.getComb(GTCombs.QUANTARIA, 16)).fluidInputs(Materials.UUMatter.getFluid(20)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Iridium)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(30464).inputs(GTCombItem.getComb(GTCombs.URANIA, 16)).fluidInputs(Materials.UUMatter.getFluid(24)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Uranium)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(31488).inputs(GTCombItem.getComb(GTCombs.PLUTONIUM, 16)).fluidInputs(Materials.UUMatter.getFluid(25)).outputs(OreDictUnifier.get(OrePrefix.dust, Materials.Plutonium)).buildAndRegister();
			RecipeMaps.AUTOCLAVE_RECIPES.recipeBuilder().EUt(384).duration(12544).inputs(GTCombItem.getComb(GTCombs.STARGATIUM, 16)).fluidInputs(Materials.UUMatter.getFluid(10)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Naquadah)).buildAndRegister();
		}

		//Comb Chemical Reactor recipes
		if (GAConfig.GTBees.ReactorRecipes) {
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.LIGNITE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Lignite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lignite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.COAL, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Coal)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Coal, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.OIL, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Oilsands)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Oilsands, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STONE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Soapstone)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Soapstone, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STONE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Apatite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Apatite, 4)).buildAndRegister();
			//RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STONE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Phosphorus)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Phosphorus, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STONE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Talc)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Talc, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STONE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Phosphate)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Phosphate, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CERTUS, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Quartzite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Quartzite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CERTUS, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.CertusQuartz)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.CertusQuartz, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CERTUS, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Barite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Barite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.REDSTONE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Cinnabar)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Cinnabar, 4)).fluidOutputs(Materials.Redstone.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.REDSTONE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Redstone)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Redstone, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.LAPIS, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Lapis)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lapis, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.LAPIS, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Lazurite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lazurite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.LAPIS, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Sodalite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Sodalite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.LAPIS, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Calcite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Calcite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.RUBY, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Redstone)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Redstone, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.RUBY, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Ruby)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Ruby, 4)).fluidOutputs(Materials.Chrome.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SAPPHIRE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Sapphire)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Sapphire, 4)).fluidOutputs(Materials.Aluminium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SAPPHIRE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.GreenSapphire)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.GreenSapphire, 4)).fluidOutputs(Materials.Aluminium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SAPPHIRE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Almandine)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Almandine, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SAPPHIRE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Pyrope)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Pyrope, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.DIAMOND, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Diamond)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Diamond, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.DIAMOND, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Graphite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Graphite, 4)).fluidOutputs(Materials.Carbon.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.OLIVINE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Magnesite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Magnesite, 4)).fluidOutputs(Materials.Magnesium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.OLIVINE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Olivine)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Olivine, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.OLIVINE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Bentonite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Bentonite, 4)).fluidOutputs(Materials.Aluminium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.OLIVINE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Glauconite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Glauconite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.EMERALD, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Emerald)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Emerald, 4)).fluidOutputs(Materials.Beryllium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.EMERALD, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Thorium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Thorium, 4)).fluidOutputs(Materials.Uranium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.EMERALD, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Beryllium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Beryllium, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SLAG, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Salt)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Salt, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SLAG, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Monazite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Monazite, 4)).fluidOutputs(Materials.Thorium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SLAG, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.RockSalt)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.RockSalt, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SLAG, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Lepidolite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lepidolite, 4)).fluidInputs(Materials.Lithium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SLAG, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Spodumene)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Spodumene, 4)).fluidOutputs(Materials.Aluminium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.COPPON, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Tetrahedrite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Tetrahedrite, 4)).fluidOutputs(Materials.Antimony.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.COPPON, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Copper)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Copper, 4)).fluidOutputs(Materials.Cobalt.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.COPPON, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Pyrite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Pyrite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.COPPON, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Stibnite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Stibnite, 4)).fluidOutputs(Materials.Antimony.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.COPPON, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Chalcopyrite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Chalcopyrite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.TINE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Cassiterite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Cassiterite, 4)).fluidOutputs(Materials.Tin.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.TINE, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Tin)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Tin, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PLUMBIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Galena)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Galena, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PLUMBIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Lead)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lead, 4)).fluidOutputs(Materials.Silver.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.FERRU, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Iron)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Iron, 4)).fluidOutputs(Materials.Nickel.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.FERRU, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.BrownLimonite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.BrownLimonite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.FERRU, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.YellowLimonite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.YellowLimonite, 4)).fluidOutputs(Materials.Nickel.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.FERRU, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.VanadiumMagnetite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.VanadiumMagnetite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.FERRU, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Magnetite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Magnetite, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.FERRU, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Pyrite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Pyrite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.FERRU, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.BandedIron)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.BandedIron, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Iron)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Iron, 4)).fluidOutputs(Materials.Nickel.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.BrownLimonite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.BrownLimonite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.YellowLimonite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.YellowLimonite, 4)).fluidOutputs(Materials.Nickel.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.VanadiumMagnetite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.VanadiumMagnetite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Magnetite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Magnetite, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Pyrite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Pyrite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.BandedIron)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.BandedIron, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Molybdenum)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Molybdenum, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STEELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Molybdenite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Molybdenite, 4)).fluidOutputs(Materials.Molybdenum.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.NICKELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Powellite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Powellite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.NICKELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Garnierite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Garnierite, 4)).fluidOutputs(Materials.Nickel.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.NICKELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Cobaltite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Cobaltite, 4)).fluidOutputs(Materials.Cobalt.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.NICKELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Nickel)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Nickel, 4)).fluidOutputs(Materials.Cobalt.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.NICKELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Pentlandite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Pentlandite, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.NICKELDUST, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Wulfenite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Wulfenite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.GALVANIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Zinc)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Zinc, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.GALVANIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Sulfur)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Sulfur, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.GALVANIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Sphalerite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Sphalerite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.ARGENTIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Silver)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Silver, 4)).fluidOutputs(Materials.Lead.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.ARGENTIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Galena)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Galena, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.AURELIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Magnetite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Magnetite, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.AURELIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Gold)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Gold, 4)).fluidOutputs(Materials.Copper.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.BAUXIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Bauxite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Bauxite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.BAUXIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Aluminium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Aluminium, 4)).buildAndRegister();
			//RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PYROLUSIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Manganese)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Manganese, 4)).fluidOutputs(Materials.Chrome.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PYROLUSIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Spessartine)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Spessartine, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PYROLUSIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Tantalite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Tantalite, 4)).fluidOutputs(Materials.Manganese.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PYROLUSIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Grossular)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Grossular, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PYROLUSIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Pyrolusite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Pyrolusite, 4)).fluidOutputs(Materials.Manganese.getFluid(144)).buildAndRegister();
			//RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.TITANIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Titanium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Titanium, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.TITANIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Ilmenite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Ilmenite, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.TITANIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Bauxite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Bauxite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CHROMIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Redstone)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Redstone, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CHROMIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Ruby)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Ruby, 4)).fluidOutputs(Materials.Chrome.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CHROMIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Chromite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Chromite, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			//RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CHROMIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Chrome)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Chrome, 4)).fluidOutputs(Materials.Iron.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CHROMIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Neodymium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Neodymium, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.CHROMIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Bastnasite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Bastnasite, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SCHEELINIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Scheelite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Scheelite, 4)).fluidOutputs(Materials.Manganese.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SCHEELINIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Lithium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Lithium, 4)).fluidOutputs(Materials.Lithium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.SCHEELINIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Tungstate)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Tungstate, 4)).fluidOutputs(Materials.Manganese.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PLATINA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Palladium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Palladium, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PLATINA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Platinum)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Platinum, 4)).fluidOutputs(Materials.Nickel.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.QUANTARIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Osmium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Osmium, 4)).fluidOutputs(Materials.Iridium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.QUANTARIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Iridium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Iridium, 4)).fluidOutputs(Materials.Platinum.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.URANIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Uranium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Uranium, 4)).fluidOutputs(Materials.Lead.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.URANIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Pitchblende)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Pitchblende, 4)).fluidOutputs(Materials.Thorium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.URANIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Uranium235)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Uranium235, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.URANIA, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Uraninite)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Uraninite, 4)).fluidOutputs(Materials.Uranium.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PLUTONIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Uranium235)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Uranium235, 4)).buildAndRegister();
			//RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.PLUTONIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Plutonium)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Plutonium, 4)).fluidOutputs(Materials.Uranium.getFluid(144)).buildAndRegister();
			//RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STARGATIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Naquadria)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Naquadria, 4)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STARGATIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.Naquadah)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.Naquadah, 4)).fluidOutputs(Materials.NaquadahEnriched.getFluid(144)).buildAndRegister();
			RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(24).duration(96).inputs(GTCombItem.getComb(GTCombs.STARGATIUM, 9), OreDictUnifier.get(OrePrefix.crushed, Materials.NaquadahEnriched)).fluidInputs(Materials.Water.getFluid(1000)).outputs(OreDictUnifier.get(OrePrefix.crushedPurified, Materials.NaquadahEnriched, 4)).fluidOutputs(Materials.Naquadah.getFluid(144)).buildAndRegister();
		}
	}
}